import { resolveLocationStateLabel } from '@baci/shared/lib';

export const NIGERIAN_STATES_FALLBACK = [
  'Abia',
  'Adamawa',
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Bayelsa',
  'Benue',
  'Borno',
  'Cross River',
  'Delta',
  'Ebonyi',
  'Edo',
  'Ekiti',
  'Enugu',
  'FCT - Abuja',
  'Gombe',
  'Imo',
  'Jigawa',
  'Kaduna',
  'Kano',
  'Katsina',
  'Kebbi',
  'Kogi',
  'Kwara',
  'Lagos',
  'Nasarawa',
  'Niger',
  'Ogun',
  'Ondo',
  'Osun',
  'Oyo',
  'Plateau',
  'Rivers',
  'Sokoto',
  'Taraba',
  'Yobe',
  'Zamfara',
];

export const NIGERIAN_CITIES_FALLBACK: Record<string, string[]> = {
  Abia: ['Aba', 'Umuahia', 'Ohafia', 'Arochukwu'],
  Adamawa: ['Yola', 'Mubi', 'Jimeta', 'Numan'],
  'Akwa Ibom': ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron', 'Abak'],
  Anambra: ['Awka', 'Onitsha', 'Nnewi', 'Ekwulobia', 'Obosi'],
  Bauchi: ['Bauchi', 'Azare', 'Misau', "Jama'are"],
  Bayelsa: ['Yenagoa', 'Ogbia', 'Brass', 'Sagbama'],
  Benue: ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala'],
  Borno: ['Maiduguri', 'Biu', 'Damboa', 'Bama'],
  'Cross River': ['Calabar', 'Ogoja', 'Ikom', 'Obudu'],
  Delta: ['Asaba', 'Warri', 'Sapele', 'Ughelli', 'Agbor', 'Effurun'],
  Ebonyi: ['Abakaliki', 'Afikpo', 'Onueke'],
  Edo: ['Benin City', 'Auchi', 'Ekpoma', 'Uromi', 'Irrua'],
  Ekiti: ['Ado Ekiti', 'Ikere Ekiti', 'Ikole Ekiti', 'Oye Ekiti'],
  Enugu: ['Enugu', 'Nsukka', 'Agbani', 'Udi'],
  'FCT - Abuja': [
    'Garki',
    'Wuse',
    'Maitama',
    'Asokoro',
    'Gwarinpa',
    'Kubwa',
    'Lugbe',
    'Nyanya',
    'Karu',
    'Jabi',
    'Utako',
    'Gudu',
    'Central Area',
    'Durumi',
    'Apo',
  ],
  Gombe: ['Gombe', 'Kumo', 'Billiri', 'Kaltungo'],
  Imo: ['Owerri', 'Orlu', 'Okigwe', 'Mbaise'],
  Jigawa: ['Dutse', 'Hadejia', 'Gumel', 'Kazaure'],
  Kaduna: ['Kaduna', 'Zaria', 'Kafanchan', 'Kagoro', 'Saminaka'],
  Kano: ['Kano', 'Fagge', 'Nassarawa', 'Wudil', 'Kumbotso'],
  Katsina: ['Katsina', 'Daura', 'Funtua', 'Malumfashi'],
  Kebbi: ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru'],
  Kogi: ['Lokoja', 'Okene', 'Idah', 'Kabba', 'Anyigba'],
  Kwara: ['Ilorin', 'Offa', 'Jebba', 'Omu-Aran'],
  Lagos: [
    'Ikeja',
    'Victoria Island',
    'Lekki',
    'Ikoyi',
    'Surulere',
    'Yaba',
    'Apapa',
    'Oshodi',
    'Mushin',
    'Agege',
    'Ajah',
    'Ikorodu',
    'Festac',
    'Isolo',
    'Maryland',
    'Ogba',
    'Gbagada',
    'Ogudu',
    'Magodo',
    'Berger',
    'Ojota',
    'Ketu',
    'Mile 2',
    'Badagry',
    'Epe',
  ],
  Nasarawa: ['Lafia', 'Keffi', 'Akwanga', 'Nasarawa'],
  Niger: ['Minna', 'Bida', 'Suleja', 'Kontagora'],
  Ogun: ['Abeokuta', 'Ijebu Ode', 'Sagamu', 'Ota', 'Ilaro', 'Sango'],
  Ondo: ['Akure', 'Ondo', 'Owo', 'Ikare', 'Ore'],
  Osun: ['Oshogbo', 'Ile-Ife', 'Ilesa', 'Ede', 'Iwo'],
  Oyo: ['Ibadan', 'Ogbomoso', 'Oyo', 'Iseyin', 'Saki'],
  Plateau: ['Jos', 'Bukuru', 'Pankshin', 'Shendam'],
  Rivers: ['Port Harcourt', 'Obio-Akpor', 'Bonny', 'Eleme', 'Okrika', 'Degema'],
  Sokoto: ['Sokoto', 'Tambuwal', 'Wurno', 'Gwadabawa'],
  Taraba: ['Jalingo', 'Wukari', 'Takum', 'Bali'],
  Yobe: ['Damaturu', 'Potiskum', 'Gashua', 'Nguru'],
  Zamfara: ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Anka'],
};

const MAX_REASONABLE_STATE_CITY_COUNT = 250;

export function getFallbackCitiesForState(state: string): string[] {
  const fallbackState = resolveLocationStateLabel(
    state,
    Object.keys(NIGERIAN_CITIES_FALLBACK)
  );
  return NIGERIAN_CITIES_FALLBACK[fallbackState] ?? [];
}

export function shouldUseFallbackCitiesForState(
  providerCities: readonly string[],
  state: string
): boolean {
  return (
    getFallbackCitiesForState(state).length > 0 &&
    providerCities.length > MAX_REASONABLE_STATE_CITY_COUNT
  );
}
