export const COUNTRIES = [
    { name: 'Nigeria', code: 'NG', currency: 'NGN', currencySymbol: '₦' },
    { name: 'Ghana', code: 'GH', currency: 'GHS', currencySymbol: '₵' },
    { name: 'Kenya', code: 'KE', currency: 'KES', currencySymbol: 'KSh' },
    { name: 'South Africa', code: 'ZA', currency: 'ZAR', currencySymbol: 'R' },
    { name: 'United States', code: 'US', currency: 'USD', currencySymbol: '$' },
    { name: 'United Kingdom', code: 'GB', currency: 'GBP', currencySymbol: '£' },
    { name: 'Canada', code: 'CA', currency: 'CAD', currencySymbol: '$' },
    { name: 'Côte d\'Ivoire', code: 'CI', currency: 'XOF', currencySymbol: 'CFA' },
    { name: 'Egypt', code: 'EG', currency: 'EGP', currencySymbol: 'E£' },
    { name: 'Rwanda', code: 'RW', currency: 'RWF', currencySymbol: 'FRw' },
    { name: 'Senegal', code: 'SN', currency: 'XOF', currencySymbol: 'CFA' },
    { name: 'Cameroon', code: 'CM', currency: 'XAF', currencySymbol: 'FCFA' },
    { name: 'Benin', code: 'BJ', currency: 'XOF', currencySymbol: 'CFA' },
    { name: 'Togo', code: 'TG', currency: 'XOF', currencySymbol: 'CFA' },
    { name: 'Mali', code: 'ML', currency: 'XOF', currencySymbol: 'CFA' },
    { name: 'Burkina Faso', code: 'BF', currency: 'XOF', currencySymbol: 'CFA' },
    { name: 'Uganda', code: 'UG', currency: 'UGX', currencySymbol: 'USh' },
    { name: 'Tanzania', code: 'TZ', currency: 'TZS', currencySymbol: 'TSh' },
    { name: 'Zambia', code: 'ZM', currency: 'ZMW', currencySymbol: 'ZK' },
    { name: 'Ethiopia', code: 'ET', currency: 'ETB', currencySymbol: 'Br' },
    { name: 'Morocco', code: 'MA', currency: 'MAD', currencySymbol: 'DH' },
    { name: 'Algeria', code: 'DZ', currency: 'DZD', currencySymbol: 'DA' },
    { name: 'Angola', code: 'AO', currency: 'AOA', currencySymbol: 'Kz' },
    { name: 'Botswana', code: 'BW', currency: 'BWP', currencySymbol: 'P' },
    { name: 'Zimbabwe', code: 'ZW', currency: 'USD', currencySymbol: '$' },
    { name: 'India', code: 'IN', currency: 'INR', currencySymbol: '₹' },
    { name: 'China', code: 'CN', currency: 'CNY', currencySymbol: '¥' },
    { name: 'Japan', code: 'JP', currency: 'JPY', currencySymbol: '¥' },
    { name: 'South Korea', code: 'KR', currency: 'KRW', currencySymbol: '₩' },
    { name: 'Germany', code: 'DE', currency: 'EUR', currencySymbol: '€' },
    { name: 'France', code: 'FR', currency: 'EUR', currencySymbol: '€' },
    { name: 'Italy', code: 'IT', currency: 'EUR', currencySymbol: '€' },
    { name: 'Spain', code: 'ES', currency: 'EUR', currencySymbol: '€' },
    { name: 'Netherlands', code: 'NL', currency: 'EUR', currencySymbol: '€' },
    { name: 'Belgium', code: 'BE', currency: 'EUR', currencySymbol: '€' },
    { name: 'Portugal', code: 'PT', currency: 'EUR', currencySymbol: '€' },
    { name: 'Sweden', code: 'SE', currency: 'SEK', currencySymbol: 'kr' },
    { name: 'Norway', code: 'NO', currency: 'NOK', currencySymbol: 'kr' },
    { name: 'Denmark', code: 'DK', currency: 'DKK', currencySymbol: 'kr' },
    { name: 'Switzerland', code: 'CH', currency: 'CHF', currencySymbol: 'Fr' },
    { name: 'Australia', code: 'AU', currency: 'AUD', currencySymbol: '$' },
    { name: 'New Zealand', code: 'NZ', currency: 'NZD', currencySymbol: '$' },
    { name: 'Brazil', code: 'BR', currency: 'BRL', currencySymbol: 'R$' },
    { name: 'Argentina', code: 'AR', currency: 'ARS', currencySymbol: '$' },
    { name: 'Chile', code: 'CL', currency: 'CLP', currencySymbol: '$' },
    { name: 'Colombia', code: 'CO', currency: 'COP', currencySymbol: '$' },
    { name: 'Mexico', code: 'MX', currency: 'MXN', currencySymbol: '$' },
    { name: 'Turkey', code: 'TR', currency: 'TRY', currencySymbol: '₺' },
    { name: 'United Arab Emirates', code: 'AE', currency: 'AED', currencySymbol: 'dh' },
    { name: 'Saudi Arabia', code: 'SA', currency: 'SAR', currencySymbol: 'SR' }
].sort((a, b) => a.name.localeCompare(b.name));
