const DNS_LABEL_MAX_LENGTH = 63;

/** Builds a DNS-safe numbered fallback for an autogenerated storefront slug. */
export function buildNumberedSlugCandidate(
  baseSlug: string,
  suffix: number
): string {
  const suffixText = `-${suffix}`;
  const maxBaseLength = DNS_LABEL_MAX_LENGTH - suffixText.length;
  const cappedBase = baseSlug
    .slice(0, maxBaseLength)
    .replace(/-+$/g, '');

  return `${cappedBase || 'store'}${suffixText}`;
}
