import { hexToHslComponents } from '@/lib/color-utils';
import type { ThemeConfiguration } from '@/lib/theme-config';

type CuratedThemeTokenProjection = Record<`--${string}`, string>;

/**
 * The complete merchant theme scope consumed by generated Puck content.
 * Keep preview and public storefront rendering on this single projection.
 */
export function getCuratedThemeTokenProjection(
  theme: ThemeConfiguration
): CuratedThemeTokenProjection {
  const { animations, borders, colors, layout, shadows, spacing, typography } =
    theme;

  return {
    '--theme-primary': colors.primary,
    '--theme-secondary': colors.secondary,
    '--theme-accent': colors.accent,
    '--theme-background': colors.background,
    '--theme-foreground': colors.foreground,
    '--theme-muted': colors.muted,
    '--theme-muted-foreground': colors.mutedForeground,
    '--theme-border': colors.border,
    '--theme-header-bg': colors.header.background,
    '--theme-header-text': colors.header.text,
    '--theme-header-icon': colors.header.iconColor,
    '--theme-header-search-border': colors.header.searchBorder,
    '--theme-header-search-bg': colors.header.searchBackground,
    '--theme-footer-bg': colors.footer.background,
    '--theme-footer-text': colors.footer.text,
    '--theme-footer-link': colors.footer.linkColor,
    '--theme-footer-link-hover': colors.footer.linkHoverColor,
    '--theme-button-primary-bg': colors.button.primary.background,
    '--theme-button-primary-text': colors.button.primary.text,
    '--theme-button-primary-hover': colors.button.primary.hover,
    '--theme-button-secondary-bg': colors.button.secondary.background,
    '--theme-button-secondary-text': colors.button.secondary.text,
    '--theme-button-secondary-hover': colors.button.secondary.hover,
    '--theme-button-accent-bg': colors.button.accent.background,
    '--theme-button-accent-text': colors.button.accent.text,
    '--theme-button-accent-hover': colors.button.accent.hover,
    '--theme-card-bg': colors.card.background,
    '--theme-card-border': colors.card.border,
    '--theme-card-text': colors.card.text,
    '--theme-input-bg': colors.input.background,
    '--theme-input-border': colors.input.border,
    '--theme-input-text': colors.input.text,
    '--theme-input-placeholder': colors.input.placeholder,
    '--theme-input-focus-border': colors.input.focusBorder,
    '--theme-font-heading': typography.fontFamily.heading,
    '--theme-font-body': typography.fontFamily.body,
    '--theme-font-mono': typography.fontFamily.mono,
    '--theme-text-xs': typography.fontSize.xs,
    '--theme-text-sm': typography.fontSize.sm,
    '--theme-text-base': typography.fontSize.base,
    '--theme-text-lg': typography.fontSize.lg,
    '--theme-text-xl': typography.fontSize.xl,
    '--theme-text-2xl': typography.fontSize['2xl'],
    '--theme-text-3xl': typography.fontSize['3xl'],
    '--theme-text-4xl': typography.fontSize['4xl'],
    '--theme-text-5xl': typography.fontSize['5xl'],
    '--theme-text-6xl': typography.fontSize['6xl'],
    '--theme-font-light': String(typography.fontWeight.light),
    '--theme-font-normal': String(typography.fontWeight.normal),
    '--theme-font-medium': String(typography.fontWeight.medium),
    '--theme-font-semibold': String(typography.fontWeight.semibold),
    '--theme-font-bold': String(typography.fontWeight.bold),
    '--theme-font-extrabold': String(typography.fontWeight.extrabold),
    '--theme-leading-tight': String(typography.lineHeight.tight),
    '--theme-leading-normal': String(typography.lineHeight.normal),
    '--theme-leading-relaxed': String(typography.lineHeight.relaxed),
    '--theme-leading-loose': String(typography.lineHeight.loose),
    '--theme-tracking-tight': typography.letterSpacing.tight,
    '--theme-tracking-normal': typography.letterSpacing.normal,
    '--theme-tracking-wide': typography.letterSpacing.wide,
    '--theme-space-xs': spacing.xs,
    '--theme-space-sm': spacing.sm,
    '--theme-space-md': spacing.md,
    '--theme-space-lg': spacing.lg,
    '--theme-space-xl': spacing.xl,
    '--theme-space-2xl': spacing['2xl'],
    '--theme-space-3xl': spacing['3xl'],
    '--theme-header-height': spacing.header.height,
    '--theme-header-px': spacing.header.paddingX,
    '--theme-header-py': spacing.header.paddingY,
    '--theme-footer-py': spacing.footer.paddingY,
    '--theme-footer-px': spacing.footer.paddingX,
    '--theme-section-py': spacing.section.paddingY,
    '--theme-section-px': spacing.section.paddingX,
    '--theme-container-max-width': spacing.container.maxWidth,
    '--theme-container-px': spacing.container.paddingX,
    '--theme-border-none': borders.width.none,
    '--theme-border-thin': borders.width.thin,
    '--theme-border-normal': borders.width.normal,
    '--theme-border-thick': borders.width.thick,
    '--theme-radius-none': borders.radius.none,
    '--theme-radius-sm': borders.radius.sm,
    '--theme-radius-md': borders.radius.md,
    '--theme-radius-lg': borders.radius.lg,
    '--theme-radius-xl': borders.radius.xl,
    '--theme-radius-2xl': borders.radius['2xl'],
    '--theme-radius-full': borders.radius.full,
    '--theme-shadow-none': shadows.none,
    '--theme-shadow-sm': shadows.sm,
    '--theme-shadow-md': shadows.md,
    '--theme-shadow-lg': shadows.lg,
    '--theme-shadow-xl': shadows.xl,
    '--theme-shadow-2xl': shadows['2xl'],
    '--theme-shadow-inner': shadows.inner,
    '--theme-duration-fast': animations.duration.fast,
    '--theme-duration-normal': animations.duration.normal,
    '--theme-duration-slow': animations.duration.slow,
    '--theme-easing-linear': animations.easing.linear,
    '--theme-easing-in': animations.easing.easeIn,
    '--theme-easing-out': animations.easing.easeOut,
    '--theme-easing-in-out': animations.easing.easeInOut,
    '--theme-z-dropdown': String(layout.zIndex.dropdown),
    '--theme-z-sticky': String(layout.zIndex.sticky),
    '--theme-z-fixed': String(layout.zIndex.fixed),
    '--theme-z-modal-backdrop': String(layout.zIndex.modalBackdrop),
    '--theme-z-modal': String(layout.zIndex.modal),
    '--theme-z-popover': String(layout.zIndex.popover),
    '--theme-z-tooltip': String(layout.zIndex.tooltip),
    '--background': hexToHslComponents(colors.background),
    '--foreground': hexToHslComponents(colors.foreground),
    '--card': hexToHslComponents(colors.card.background),
    '--card-foreground': hexToHslComponents(colors.card.text),
    '--popover': hexToHslComponents(colors.card.background),
    '--popover-foreground': hexToHslComponents(colors.card.text),
    '--primary': hexToHslComponents(colors.primary),
    '--primary-foreground': hexToHslComponents(colors.button.primary.text),
    '--secondary': hexToHslComponents(colors.button.secondary.background),
    '--secondary-foreground': hexToHslComponents(colors.button.secondary.text),
    '--destructive': hexToHslComponents('#B91C1C'),
    '--destructive-foreground': hexToHslComponents('#FFFFFF'),
    '--muted': hexToHslComponents(colors.muted),
    '--muted-foreground': hexToHslComponents(colors.mutedForeground),
    '--accent': hexToHslComponents(colors.accent),
    '--accent-foreground': hexToHslComponents(colors.button.accent.text),
    '--border': hexToHslComponents(colors.border),
    '--input': hexToHslComponents(colors.input.border),
    '--ring': hexToHslComponents(colors.primary),
    '--store-primary': colors.primary,
    '--store-primary-text': colors.button.primary.text,
    '--store-on-primary': colors.button.primary.text,
    '--store-secondary': colors.button.secondary.background,
    '--store-secondary-text': colors.button.secondary.text,
    '--store-accent': colors.accent,
    '--store-accent-text': colors.button.accent.text,
    '--store-background': colors.background,
    '--store-background-text': colors.foreground,
    '--store-foreground': colors.foreground,
    '--store-border': colors.border,
    '--store-rating': colors.accent,
    '--store-option-secondary': colors.button.secondary.background,
  };
}
