export const forbiddenCuratedStorefrontClaims = [
  'free shipping',
  'nationwide delivery',
  'easy payments',
  'flexible payment',
  'premium quality',
  'trusted quality',
  'trusted by',
  'best seller',
  'expert',
  'expert advice',
  'warranty',
  'fresh meals',
  'popular',
  'delivery-ready',
  'trusted fulfillment',
  'buy with confidence',
  'careful delivery promises',
  'fulfillment',
  'confidence',
  'quality products',
  'secure checkout',
  'reliable',
  'exclusive offers',
] as const;
