import { Platform, StyleSheet } from 'react-native';
import { BRAND, palette, RADIUS, SHADOWS, SPACING } from '@/constants/Colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: palette.gray[100],
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  headerTitle: {
    fontSize: 22,
    fontFamily: 'Inter_700Bold',
  },
  headerCount: {
    fontSize: 16,
    fontFamily: 'Inter_500Medium',
  },
  clearText: {
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: SPACING.md,
    gap: SPACING.md,
  },
  cartCard: {
    borderRadius: RADIUS['2xl'],
    padding: SPACING.md,
    ...SHADOWS.sm,
    borderWidth: 1,
  },
  cardTop: {
    flexDirection: 'row',
    gap: SPACING.md,
  },
  imageContainer: {
    width: 80,
    height: 80,
    backgroundColor: palette.gray[50],
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    borderColor: palette.gray[100],
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  productInfo: {
    flex: 1,
    paddingRight: 24,
  },
  productName: {
    fontSize: 14,
    fontFamily: 'Inter_700Bold',
    color: palette.gray[900],
    lineHeight: 18,
    marginBottom: 8,
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  conditionTag: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
  },
  conditionTagNew: {},
  conditionTagUsed: {},
  conditionTagText: {
    fontSize: 9,
    fontFamily: 'Inter_700Bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  conditionTagTextNew: {},
  conditionTagTextUsed: {},
  colorTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: palette.gray[50],
    borderWidth: 1,
    borderColor: palette.gray[100],
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  colorDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: palette.gray[300],
  },
  colorTagText: {
    fontSize: 10,
    color: palette.gray[600],
  },
  storageTag: {
    backgroundColor: palette.gray[50],
    borderWidth: 1,
    borderColor: palette.gray[100],
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  storageTagText: {
    fontSize: 10,
    color: palette.gray[600],
  },
  removeButton: {
    position: 'absolute',
    top: 0,
    right: 0,
    padding: 4,
  },
  dashedSeparator: {
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: palette.gray[100],
    marginVertical: SPACING.md,
  },
  controlsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: palette.gray[50],
    borderWidth: 1,
    borderColor: palette.gray[200],
    borderRadius: RADIUS.lg,
    height: 36,
  },
  quantityButton: {
    width: 36,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityText: {
    fontSize: 14,
    fontFamily: 'Inter_700Bold',
    color: palette.gray[900],
    minWidth: 28,
    textAlign: 'center',
  },
  priceContainer: {
    alignItems: 'flex-end',
  },
  originalPrice: {
    fontSize: 10,
    color: palette.gray[400],
    textDecorationLine: 'line-through',
    fontFamily: 'Inter_400Regular',
  },
  negotiatedPrice: {
    fontSize: 18,
    fontFamily: 'Inter_700Bold',
  },
  currentPrice: {
    fontSize: 18,
    fontFamily: 'Inter_700Bold',
    color: palette.gray[900],
  },
  solidSeparator: {
    height: 1,
    backgroundColor: palette.gray[100],
    marginTop: SPACING.md,
  },
  bottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: SPACING.md,
    gap: SPACING.sm,
  },
  assuranceContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  toggle: {
    width: 36,
    height: 20,
    borderRadius: 10,
    backgroundColor: palette.gray[200],
    padding: 2,
    justifyContent: 'center',
  },
  toggleActive: {
    backgroundColor: BRAND.primary,
  },
  toggleKnob: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  toggleKnobActive: {
    alignSelf: 'flex-end',
  },
  assuranceInfo: {
    flex: 1,
  },
  assuranceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  assuranceTitle: {
    fontSize: 11,
    fontFamily: 'Inter_700Bold',
    color: palette.gray[800],
  },
  assuranceDesc: {
    fontSize: 10,
    color: palette.gray[500],
    marginTop: 2,
  },
  negotiateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: palette.red[100],
  },
  negotiateButtonText: {
    fontSize: 12,
    fontFamily: 'Inter_700Bold',
    color: BRAND.primary,
  },
  negotiatedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
  },
  negotiatedBadgeText: {
    fontSize: 12,
    fontFamily: 'Inter_700Bold',
  },
  checkoutStickyFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.sm,
    paddingBottom: Platform.OS === 'ios' ? 24 : 20,
    borderTopWidth: 1,
    ...SHADOWS.lg,
    zIndex: 1000,
  },
  bulkHint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: palette.gray[50],
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.sm,
    alignSelf: 'stretch',
    borderWidth: 1,
    borderColor: palette.gray[100],
  },
  footerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  bulkButton: {
    width: 90,
    height: 56,
    backgroundColor: palette.gray[50],
    borderRadius: RADIUS.xl,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: palette.gray[200],
    marginLeft: 8,
  },
  bulkButtonContent: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  checkoutButtonContainer: {
    flex: 1,
    height: 56,
  },
  checkoutButtonContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  checkoutBtnLabel: {
    fontSize: 15,
    fontFamily: 'Inter_700Bold',
  },
  checkoutBtnDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  checkoutBtnPrice: {
    fontSize: 15,
    fontFamily: 'Inter_700Bold',
  },
  bulkHintText: {
    fontSize: 9,
    color: palette.gray[500],
    fontFamily: 'Inter_500Medium',
  },
  bulkButtonDisabled: {
    opacity: 0.6,
  },
  bulkButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.96 }],
  },
  bulkButtonText: {
    fontSize: 11,
    fontFamily: 'Inter_700Bold',
    color: palette.gray[700],
    textAlign: 'center',
  },
  redCheckoutButton: {
    height: 56,
    borderRadius: RADIUS.xl,
    justifyContent: 'center',
    alignItems: 'center',
    ...SHADOWS.md,
    zIndex: 100,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  redCheckoutButtonPressed: {
    transform: [{ scale: 0.98 }],
  },
  checkoutButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  redCheckoutButtonText: {
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
  },
  checkoutDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  redCheckoutPriceText: {
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
  },
  summaryCard: {
    marginTop: SPACING.md,
    borderRadius: RADIUS['2xl'],
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: palette.gray[100],
    marginBottom: SPACING.md,
  },
  secureBadgeInside: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: SPACING.xl,
  },
  summaryTitle: {
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
    color: palette.gray[900],
    marginBottom: SPACING.sm,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  summaryLabelWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  summaryLabel: {
    fontSize: 13,
    color: palette.gray[600],
  },
  summaryValue: {
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    color: palette.gray[900],
  },
  assurancePercentBadge: {
    backgroundColor: palette.red[50],
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.red[100],
  },
  assurancePercentText: {
    fontSize: 9,
    fontFamily: 'Inter_700Bold',
    color: BRAND.primary,
  },
  summaryDivider: {
    height: 1,
    backgroundColor: palette.gray[200],
    marginVertical: 8,
    borderStyle: 'dashed',
  },
  totalLabel: {
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
    color: palette.gray[900],
  },
  totalValue: {
    fontSize: 18,
    fontFamily: 'Inter_700Bold',
    color: palette.gray[900],
  },
  checkoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    borderRadius: RADIUS.xl,
    ...SHADOWS.lg,
  },
  checkoutButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  checkoutButtonDisabled: {
    opacity: 0.7,
  },
  checkoutButtonText: {
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
  },
  secureBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: SPACING.md,
  },
  secureBadgeText: {
    fontSize: 12,
    color: palette.gray[400],
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: SPACING.xl,
  },
  emptyIconBg: {
    width: 120,
    height: 120,
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SPACING.lg,
  },
  emptyTitle: {
    fontSize: 22,
    fontFamily: 'Inter_700Bold',
    marginBottom: SPACING.sm,
  },
  emptySubtitle: {
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: SPACING.xl,
  },
  shopButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderRadius: RADIUS.xl,
    ...SHADOWS.lg,
  },
  shopButtonText: {
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
  },
  warningOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  warningBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  warningModal: {
    borderRadius: 20,
    padding: 28,
    width: '100%',
    maxWidth: 400,
    ...SHADOWS.xl,
  },
  warningHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 18,
  },
  warningIconCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    justifyContent: 'center',
    alignItems: 'center',
  },
  warningTitle: {
    flex: 1,
    fontSize: 22,
    fontFamily: 'Inter_700Bold',
    color: palette.gray[900],
  },
  warningDescription: {
    fontSize: 15,
    lineHeight: 24,
    color: palette.gray[600],
    marginBottom: 22,
  },
  warningDescriptionBold: {
    fontFamily: 'Inter_600SemiBold',
  },
  warningButtons: {
    gap: 12,
  },
  warningPrimaryButton: {
    backgroundColor: BRAND.primary,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
  },
  warningPrimaryButtonText: {
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
  },
  warningSecondaryButton: {
    paddingVertical: 14,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
  },
  warningSecondaryButtonText: {
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
    color: palette.gray[800],
  },
  warningCancelButton: {
    paddingVertical: 10,
    alignItems: 'center',
  },
  warningCancelButtonText: {
    fontSize: 15,
    fontFamily: 'Inter_500Medium',
    color: palette.gray[500],
  },
  warningButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
});

export default styles;
