import type { Config } from 'tailwindcss';
import baseConfig from './tailwind.config';

export default {
  ...baseConfig,
  content: [
    './src/app/(storefront)/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/analytics/analytics-provider.tsx',
    './src/components/analytics/deferred-google-store-widget.tsx',
    './src/components/analytics/google-customer-reviews.tsx',
    './src/components/blog/renderer/BlogContentRenderer.tsx',
    './src/components/blog/table-of-contents.tsx',
    './src/components/storefront/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/themed/**/*.{js,ts,jsx,tsx,mdx}',
    // Keep UI entries selective so storefront CSS does not absorb dashboard/admin utilities.
    './src/components/ui/accordion.tsx',
    './src/components/ui/alert.tsx',
    './src/components/ui/animated-icons.tsx',
    './src/components/ui/badge.tsx',
    './src/components/ui/button.tsx',
    './src/components/ui/card.tsx',
    './src/components/ui/carousel.tsx',
    './src/components/ui/checkbox.tsx',
    './src/components/ui/dialog.tsx',
    './src/components/ui/dropdown-menu.tsx',
    './src/components/ui/form.tsx',
    './src/components/ui/input.tsx',
    './src/components/ui/label.tsx',
    './src/components/ui/password-input.tsx',
    './src/components/ui/phone-input.tsx',
    './src/components/ui/progress.tsx',
    './src/components/ui/radio-group.tsx',
    './src/components/ui/safe-html.tsx',
    './src/components/ui/select.tsx',
    './src/components/ui/separator.tsx',
    './src/components/ui/sheet.tsx',
    './src/components/ui/skeleton.tsx',
    './src/components/ui/skeletons.tsx',
    './src/components/ui/tabs.tsx',
    './src/components/ui/textarea.tsx',
    './src/components/ui/tooltip.tsx',
    './src/components/address-autocomplete.tsx',
    './src/components/app-body.tsx',
    './src/components/builder/icon-registry.tsx',
    './src/components/cart.tsx',
    './src/components/checkout-theme-provider.tsx',
    './src/components/logo.tsx',
    './src/components/optimized-image.tsx',
    './src/templates/**/*.{js,ts,jsx,tsx,mdx}',
  ],
} satisfies Config;
