export const createGithubAppTokenPostReceipt = Object.freeze({
  action: 'actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1',
  actionYamlSha256:
    '2c4c77d1cafa8d792ab4a9d449799221baf95176a47692ad9a0b350b0a2618ed',
  bundlePath: 'dist/post.cjs',
  bundleSha256:
    'c127db2f86238e3b57a5a57120a1de5f1b873006ee5b60c56b871de83dd7dfe2',
  sourceRange: Object.freeze({ firstLine: 20984, lastLine: 21016 }),
  sourceSha256:
    'b734f35f5483b4d771a0e3ee2e88136df25bb1b6f9068c203ed3086564aa3712',
  source: [
    '// lib/post.js',
    'async function post(core, request2) {',
    '  const skipTokenRevoke = core.getBooleanInput("skip-token-revoke");',
    '  if (skipTokenRevoke) {',
    '    core.info("Token revocation was skipped");',
    '    return;',
    '  }',
    '  const token = core.getState("token");',
    '  if (!token) {',
    '    core.info("Token is not set");',
    '    return;',
    '  }',
    '  const expiresAt = core.getState("expiresAt");',
    '  if (expiresAt && tokenExpiresIn(expiresAt) < 0) {',
    '    core.info("Token expired, skipping token revocation");',
    '    return;',
    '  }',
    '  try {',
    '    await request2("DELETE /installation/token", {',
    '      headers: {',
    '        authorization: `token ${token}`',
    '      }',
    '    });',
    '    core.info("Token revoked");',
    '  } catch (error2) {',
    '    core.warning(`Token revocation failed: ${error2.message}`);',
    '  }',
    '}',
    'function tokenExpiresIn(expiresAt) {',
    '  const now = /* @__PURE__ */ new Date();',
    '  const expiresAtDate = new Date(expiresAt);',
    '  return Math.round((expiresAtDate.getTime() - now.getTime()) / 1e3);',
    '}',
    '',
  ].join('\n'),
});
