query GetCodeScanningAlerts(
  $owner: String!
  $name: String!
  $endCursor: String
) {
  repository(owner: $owner, name: $name) {
    codeScanningAlerts(first: 100, after: $endCursor, state: OPEN) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        number
        createdAt
        state
        rule {
          id
          severity
          description
          tags
        }
        tool {
          name
        }
        mostRecentInstance {
          location {
            path
            startLine
            endLine
          }
          message {
            text
          }
          classification
        }
      }
    }
  }
}
