#!/bin/bash
# Image Renaming Script
# Generated by migrate-images-vps.ts

mkdir -p /var/www/cdn/products/migrated

[ -f "/var/www/cdn/products/productImages-1755110938551-OIK6SL.avif" ] && mv "/var/www/cdn/products/productImages-1755110938551-OIK6SL.avif" "/var/www/cdn/products/dell-xps-15-9560-black.avif"
[ -f "/var/www/cdn/products/productImages-1755110938553-Z0N0L9.avif" ] && mv "/var/www/cdn/products/productImages-1755110938553-Z0N0L9.avif" "/var/www/cdn/products/dell-xps-15-9560-silver.avif"

echo "✅ Renamed 2 files"
