import type { CSSProperties } from 'react';

const errorFontStack =
  'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';

export const systemErrorStyles = {
  page: {
    alignItems: 'center',
    background:
      'radial-gradient(circle at top, rgba(79, 70, 229, 0.08), transparent 32rem), #f8fafc',
    boxSizing: 'border-box',
    color: '#0f172a',
    display: 'flex',
    fontFamily: errorFontStack,
    inset: 0,
    justifyContent: 'center',
    minHeight: '100vh',
    overflowX: 'hidden',
    overflowY: 'auto',
    padding: '1.5rem',
    position: 'fixed',
  },
  shell: {
    margin: '0 auto',
    maxWidth: '42rem',
    textAlign: 'center',
    width: '100%',
  },
  card: {
    background: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '1.25rem',
    boxShadow: '0 24px 80px rgba(15, 23, 42, 0.12)',
    boxSizing: 'border-box',
    margin: '0 auto',
    maxWidth: '30rem',
    padding: '2rem',
    textAlign: 'center',
    width: '100%',
  },
  brand: {
    color: '#4f46e5',
    display: 'inline-block',
    fontSize: '0.875rem',
    fontWeight: 800,
    letterSpacing: '0.08em',
    marginBottom: '1rem',
    textDecoration: 'none',
    textTransform: 'uppercase',
  },
  statusCode: {
    color: 'rgba(79, 70, 229, 0.12)',
    fontSize: 'clamp(5rem, 18vw, 10rem)',
    fontWeight: 900,
    lineHeight: 0.85,
    margin: '0 0 0.75rem',
  },
  icon: {
    alignItems: 'center',
    background: '#fee2e2',
    borderRadius: 999,
    color: '#dc2626',
    display: 'inline-flex',
    fontSize: '1.5rem',
    fontWeight: 800,
    height: '4rem',
    justifyContent: 'center',
    marginBottom: '1.25rem',
    width: '4rem',
  },
  title: {
    color: '#0f172a',
    fontSize: 'clamp(1.875rem, 5vw, 3rem)',
    fontWeight: 800,
    lineHeight: 1.08,
    margin: 0,
  },
  cardTitle: {
    color: '#0f172a',
    fontSize: 'clamp(1.5rem, 4vw, 2rem)',
    fontWeight: 800,
    lineHeight: 1.08,
    margin: 0,
  },
  copy: {
    color: '#475569',
    fontSize: '1rem',
    lineHeight: 1.7,
    margin: '1rem auto 0',
    maxWidth: '34rem',
  },
  actions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.75rem',
    justifyContent: 'center',
    marginTop: '1.75rem',
  },
  button: {
    alignItems: 'center',
    background: '#4f46e5',
    border: '1px solid #4f46e5',
    borderRadius: 999,
    color: '#ffffff',
    cursor: 'pointer',
    display: 'inline-flex',
    font: 'inherit',
    fontWeight: 700,
    justifyContent: 'center',
    minHeight: '3rem',
    minWidth: '9rem',
    padding: '0.75rem 1.25rem',
    textDecoration: 'none',
  },
  buttonSecondary: {
    background: 'transparent',
    color: '#4f46e5',
  },
  debug: {
    background: 'rgba(15, 23, 42, 0.06)',
    borderRadius: '0.75rem',
    color: '#475569',
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontSize: '0.75rem',
    marginTop: '1.5rem',
    maxHeight: '12rem',
    overflow: 'auto',
    padding: '1rem',
    textAlign: 'left',
    whiteSpace: 'pre-wrap',
  },
} satisfies Record<string, CSSProperties>;
