export const MERCHANT_COUNTRIES = [
  {
    name: 'United States',
    code: 'US',
    flag: '🇺🇸',
    currency: 'USD',
    phoneCode: '+1',
    currencySymbol: '$',
  },
  {
    name: 'Nigeria',
    code: 'NG',
    flag: '🇳🇬',
    currency: 'NGN',
    phoneCode: '+234',
    currencySymbol: '₦',
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    flag: '🇬🇧',
    currency: 'GBP',
    phoneCode: '+44',
    currencySymbol: '£',
  },
  {
    name: 'Canada',
    code: 'CA',
    flag: '🇨🇦',
    currency: 'CAD',
    phoneCode: '+1',
    currencySymbol: '$',
  },
  {
    name: 'Australia',
    code: 'AU',
    flag: '🇦🇺',
    currency: 'AUD',
    phoneCode: '+61',
    currencySymbol: '$',
  },
  {
    name: 'Germany',
    code: 'DE',
    flag: '🇩🇪',
    currency: 'EUR',
    phoneCode: '+49',
    currencySymbol: '€',
  },
  {
    name: 'France',
    code: 'FR',
    flag: '🇫🇷',
    currency: 'EUR',
    phoneCode: '+33',
    currencySymbol: '€',
  },
  {
    name: 'Japan',
    code: 'JP',
    flag: '🇯🇵',
    currency: 'JPY',
    phoneCode: '+81',
    currencySymbol: '¥',
  },
  {
    name: 'India',
    code: 'IN',
    flag: '🇮🇳',
    currency: 'INR',
    phoneCode: '+91',
    currencySymbol: '₹',
  },
  {
    name: 'Brazil',
    code: 'BR',
    flag: '🇧🇷',
    currency: 'BRL',
    phoneCode: '+55',
    currencySymbol: 'R$',
  },
  {
    name: 'South Africa',
    code: 'ZA',
    flag: '🇿🇦',
    currency: 'ZAR',
    phoneCode: '+27',
    currencySymbol: 'R',
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    flag: '🇦🇪',
    currency: 'AED',
    phoneCode: '+971',
    currencySymbol: 'د.إ',
  },
  {
    name: 'Kenya',
    code: 'KE',
    flag: '🇰🇪',
    currency: 'KES',
    phoneCode: '+254',
    currencySymbol: 'KSh',
  },
  {
    name: 'Ghana',
    code: 'GH',
    flag: '🇬🇭',
    currency: 'GHS',
    phoneCode: '+233',
    currencySymbol: 'GH₵',
  },
  {
    name: 'Egypt',
    code: 'EG',
    flag: '🇪🇬',
    currency: 'EGP',
    phoneCode: '+20',
    currencySymbol: 'E£',
  },
  {
    name: 'Cameroon',
    code: 'CM',
    flag: '🇨🇲',
    currency: 'XAF',
    phoneCode: '+237',
    currencySymbol: 'FCFA',
  },
  {
    name: "Côte d'Ivoire",
    code: 'CI',
    flag: '🇨🇮',
    currency: 'XOF',
    phoneCode: '+225',
    currencySymbol: 'CFA',
  },
  {
    name: 'Senegal',
    code: 'SN',
    flag: '🇸🇳',
    currency: 'XOF',
    phoneCode: '+221',
    currencySymbol: 'CFA',
  },
  {
    name: 'Burkina Faso',
    code: 'BF',
    flag: '🇧🇫',
    currency: 'XOF',
    phoneCode: '+226',
    currencySymbol: 'CFA',
  },
  {
    name: 'Rwanda',
    code: 'RW',
    flag: '🇷🇼',
    currency: 'RWF',
    phoneCode: '+250',
    currencySymbol: 'FRw',
  },
  {
    name: 'Tanzania',
    code: 'TZ',
    flag: '🇹🇿',
    currency: 'TZS',
    phoneCode: '+255',
    currencySymbol: 'TSh',
  },
  {
    name: 'Uganda',
    code: 'UG',
    flag: '🇺🇬',
    currency: 'UGX',
    phoneCode: '+256',
    currencySymbol: 'USh',
  },
] as const;
