import { StyleSheet } from 'react-native';
import { BRAND, RADIUS, SHADOWS, SPACING, TYPOGRAPHY } from '@/constants/Colors';

export const permissionModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.lg,
  },
  card: {
    width: '100%',
    maxWidth: 348,
    borderRadius: RADIUS['3xl'],
    paddingHorizontal: SPACING.xl,
    paddingTop: 0,
    paddingBottom: 36,
    alignItems: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    ...SHADOWS.xl,
  },
  accentStripe: {
    width: '100%',
    height: 3,
    marginBottom: 28,
  },
  iconStage: {
    width: 96,
    height: 96,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SPACING.lg,
  },
  diamond: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: RADIUS['2xl'],
    transform: [{ rotate: '45deg' }],
    borderWidth: 1,
  },
  iconCircle: {
    width: 56,
    height: 56,
    borderRadius: RADIUS.full,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  label: {
    fontSize: TYPOGRAPHY.size.xs,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 1.5,
    paddingHorizontal: SPACING.md,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    overflow: 'hidden',
    marginBottom: SPACING.md,
  },
  title: {
    fontSize: TYPOGRAPHY.size.xl,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: SPACING.sm,
    letterSpacing: -0.5,
  },
  message: {
    fontSize: TYPOGRAPHY.size.sm,
    fontFamily: 'Inter_400Regular',
    fontWeight: '400',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 28,
    paddingHorizontal: SPACING.xs,
  },
  actions: {
    width: '100%',
    gap: SPACING.sm,
  },
  primaryButton: {
    width: '100%',
    height: 54,
    borderRadius: RADIUS.xl,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: BRAND.primary,
    ...SHADOWS.lg,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: TYPOGRAPHY.size.base,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  secondaryButton: {
    width: '100%',
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: RADIUS.lg,
  },
  secondaryButtonText: {
    fontSize: TYPOGRAPHY.size.sm,
    fontFamily: 'Inter_500Medium',
    fontWeight: '500',
    textAlign: 'center',
  },
});
