export interface Country {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
  maxLength?: number;
}

export const COUNTRIES: Country[] = [
  { code: 'NG', name: 'Nigeria', dialCode: '+234', flag: '🇳🇬', maxLength: 10 },
  { code: 'DZ', name: 'Algeria', dialCode: '+213', flag: '🇩🇿', maxLength: 9 },
  { code: 'AO', name: 'Angola', dialCode: '+244', flag: '🇦🇴', maxLength: 9 },
  { code: 'AR', name: 'Argentina', dialCode: '+54', flag: '🇦🇷', maxLength: 10 },
  { code: 'AU', name: 'Australia', dialCode: '+61', flag: '🇦🇺', maxLength: 9 },
  { code: 'AT', name: 'Austria', dialCode: '+43', flag: '🇦🇹', maxLength: 10 },
  { code: 'BH', name: 'Bahrain', dialCode: '+973', flag: '🇧🇭', maxLength: 8 },
  {
    code: 'BD',
    name: 'Bangladesh',
    dialCode: '+880',
    flag: '🇧🇩',
    maxLength: 10,
  },
  { code: 'BE', name: 'Belgium', dialCode: '+32', flag: '🇧🇪', maxLength: 9 },
  { code: 'BJ', name: 'Benin', dialCode: '+229', flag: '🇧🇯', maxLength: 8 },
  { code: 'BR', name: 'Brazil', dialCode: '+55', flag: '🇧🇷', maxLength: 11 },
  {
    code: 'BF',
    name: 'Burkina Faso',
    dialCode: '+226',
    flag: '🇧🇫',
    maxLength: 8,
  },
  { code: 'CM', name: 'Cameroon', dialCode: '+237', flag: '🇨🇲', maxLength: 9 },
  { code: 'CA', name: 'Canada', dialCode: '+1', flag: '🇨🇦', maxLength: 10 },
  { code: 'TD', name: 'Chad', dialCode: '+235', flag: '🇹🇩', maxLength: 8 },
  { code: 'CN', name: 'China', dialCode: '+86', flag: '🇨🇳', maxLength: 11 },
  {
    code: 'CD',
    name: 'Congo (DRC)',
    dialCode: '+243',
    flag: '🇨🇩',
    maxLength: 9,
  },
  {
    code: 'CI',
    name: "Cote d'Ivoire",
    dialCode: '+225',
    flag: '🇨🇮',
    maxLength: 10,
  },
  { code: 'EG', name: 'Egypt', dialCode: '+20', flag: '🇪🇬', maxLength: 10 },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251', flag: '🇪🇹', maxLength: 9 },
  { code: 'FI', name: 'Finland', dialCode: '+358', flag: '🇫🇮', maxLength: 10 },
  { code: 'FR', name: 'France', dialCode: '+33', flag: '🇫🇷', maxLength: 9 },
  { code: 'GA', name: 'Gabon', dialCode: '+241', flag: '🇬🇦', maxLength: 8 },
  { code: 'GM', name: 'Gambia', dialCode: '+220', flag: '🇬🇲', maxLength: 7 },
  { code: 'DE', name: 'Germany', dialCode: '+49', flag: '🇩🇪', maxLength: 11 },
  { code: 'GH', name: 'Ghana', dialCode: '+233', flag: '🇬🇭', maxLength: 9 },
  { code: 'GN', name: 'Guinea', dialCode: '+224', flag: '🇬🇳', maxLength: 9 },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', flag: '🇭🇰', maxLength: 8 },
  { code: 'IN', name: 'India', dialCode: '+91', flag: '🇮🇳', maxLength: 10 },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', flag: '🇮🇩', maxLength: 11 },
  { code: 'IE', name: 'Ireland', dialCode: '+353', flag: '🇮🇪', maxLength: 9 },
  { code: 'IL', name: 'Israel', dialCode: '+972', flag: '🇮🇱', maxLength: 9 },
  { code: 'IT', name: 'Italy', dialCode: '+39', flag: '🇮🇹', maxLength: 10 },
  { code: 'JP', name: 'Japan', dialCode: '+81', flag: '🇯🇵', maxLength: 10 },
  { code: 'KE', name: 'Kenya', dialCode: '+254', flag: '🇰🇪', maxLength: 9 },
  { code: 'KW', name: 'Kuwait', dialCode: '+965', flag: '🇰🇼', maxLength: 8 },
  { code: 'LR', name: 'Liberia', dialCode: '+231', flag: '🇱🇷', maxLength: 9 },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', flag: '🇲🇾', maxLength: 10 },
  { code: 'ML', name: 'Mali', dialCode: '+223', flag: '🇲🇱', maxLength: 8 },
  { code: 'MX', name: 'Mexico', dialCode: '+52', flag: '🇲🇽', maxLength: 10 },
  { code: 'MA', name: 'Morocco', dialCode: '+212', flag: '🇲🇦', maxLength: 9 },
  {
    code: 'MZ',
    name: 'Mozambique',
    dialCode: '+258',
    flag: '🇲🇿',
    maxLength: 9,
  },
  {
    code: 'NL',
    name: 'Netherlands',
    dialCode: '+31',
    flag: '🇳🇱',
    maxLength: 9,
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    dialCode: '+64',
    flag: '🇳🇿',
    maxLength: 9,
  },
  { code: 'NE', name: 'Niger', dialCode: '+227', flag: '🇳🇪', maxLength: 8 },
  { code: 'NO', name: 'Norway', dialCode: '+47', flag: '🇳🇴', maxLength: 8 },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: '🇵🇰', maxLength: 10 },
  {
    code: 'PH',
    name: 'Philippines',
    dialCode: '+63',
    flag: '🇵🇭',
    maxLength: 10,
  },
  { code: 'PL', name: 'Poland', dialCode: '+48', flag: '🇵🇱', maxLength: 9 },
  { code: 'PT', name: 'Portugal', dialCode: '+351', flag: '🇵🇹', maxLength: 9 },
  { code: 'QA', name: 'Qatar', dialCode: '+974', flag: '🇶🇦', maxLength: 8 },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', flag: '🇷🇼', maxLength: 9 },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    dialCode: '+966',
    flag: '🇸🇦',
    maxLength: 9,
  },
  { code: 'SN', name: 'Senegal', dialCode: '+221', flag: '🇸🇳', maxLength: 9 },
  {
    code: 'SL',
    name: 'Sierra Leone',
    dialCode: '+232',
    flag: '🇸🇱',
    maxLength: 8,
  },
  { code: 'SG', name: 'Singapore', dialCode: '+65', flag: '🇸🇬', maxLength: 8 },
  {
    code: 'ZA',
    name: 'South Africa',
    dialCode: '+27',
    flag: '🇿🇦',
    maxLength: 9,
  },
  {
    code: 'KR',
    name: 'South Korea',
    dialCode: '+82',
    flag: '🇰🇷',
    maxLength: 10,
  },
  { code: 'ES', name: 'Spain', dialCode: '+34', flag: '🇪🇸', maxLength: 9 },
  { code: 'SE', name: 'Sweden', dialCode: '+46', flag: '🇸🇪', maxLength: 9 },
  {
    code: 'CH',
    name: 'Switzerland',
    dialCode: '+41',
    flag: '🇨🇭',
    maxLength: 9,
  },
  { code: 'TZ', name: 'Tanzania', dialCode: '+255', flag: '🇹🇿', maxLength: 9 },
  { code: 'TG', name: 'Togo', dialCode: '+228', flag: '🇹🇬', maxLength: 8 },
  { code: 'TR', name: 'Turkey', dialCode: '+90', flag: '🇹🇷', maxLength: 10 },
  { code: 'UG', name: 'Uganda', dialCode: '+256', flag: '🇺🇬', maxLength: 9 },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    dialCode: '+971',
    flag: '🇦🇪',
    maxLength: 9,
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    dialCode: '+44',
    flag: '🇬🇧',
    maxLength: 11,
  },
  {
    code: 'US',
    name: 'United States',
    dialCode: '+1',
    flag: '🇺🇸',
    maxLength: 10,
  },
  { code: 'ZM', name: 'Zambia', dialCode: '+260', flag: '🇿🇲', maxLength: 9 },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼', maxLength: 9 },
];
