/**
 * Mock products for Lumina template in preview mode
 */
import type { Product } from '@/lib/products';

export const mockProducts: Product[] = [
    {
        id: 'mock-1',
        name: 'Elegant Watch',
        description: 'A stunning timepiece for the modern professional',
        status: 'active',
        price: 45000000, // 450,000 in kobo
        manage_stock: false,
        stock: 10,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
        imageLarge: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1200',
        imageHint: 'watch accessory',
        brand: 'Lumina',
        gtin: '',
        mpn: '',
        category: 'Accessories',
        condition: 'new',
        rating: 4.8,
        review_count: 124,
        colors: ['Silver', 'Gold', 'Rose Gold'],
    },
    {
        id: 'mock-2',
        name: 'Premium Leather Bag',
        description: 'Handcrafted Italian leather handbag',
        status: 'active',
        price: 75000000,
        manage_stock: false,
        stock: 5,
        image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800',
        imageLarge: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=1200',
        imageHint: 'leather bag',
        brand: 'Artisan',
        gtin: '',
        mpn: '',
        category: 'Bags',
        condition: 'new',
        rating: 4.9,
        review_count: 89,
        colors: ['Black', 'Brown', 'Tan'],
    },
    {
        id: 'mock-3',
        name: 'Designer Sunglasses',
        description: 'UV protection with style',
        status: 'active',
        price: 28000000,
        manage_stock: false,
        stock: 15,
        image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800',
        imageLarge: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=1200',
        imageHint: 'sunglasses',
        brand: 'Luxe',
        gtin: '',
        mpn: '',
        category: 'Accessories',
        condition: 'new',
        rating: 4.6,
        review_count: 156,
    },
    {
        id: 'mock-4',
        name: 'Silk Scarf',
        description: 'Pure silk scarf with hand-painted design',
        status: 'active',
        price: 12000000,
        manage_stock: false,
        stock: 20,
        image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800',
        imageLarge: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=1200',
        imageHint: 'silk scarf',
        brand: 'Lumina',
        gtin: '',
        mpn: '',
        category: 'Accessories',
        condition: 'new',
        rating: 4.7,
        review_count: 78,
        colors: ['Navy', 'Burgundy', 'Ivory'],
    },
    {
        id: 'mock-5',
        name: 'Minimalist Wallet',
        description: 'Slim RFID-blocking leather wallet',
        status: 'active',
        price: 8500000,
        manage_stock: false,
        stock: 30,
        image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800',
        imageLarge: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=1200',
        imageHint: 'wallet leather',
        brand: 'Essential',
        gtin: '',
        mpn: '',
        category: 'Accessories',
        condition: 'new',
        rating: 4.5,
        review_count: 203,
        colors: ['Black', 'Navy'],
    },
    {
        id: 'mock-6',
        name: 'Pearl Earrings',
        description: 'Freshwater pearl drop earrings',
        status: 'active',
        price: 35000000,
        manage_stock: false,
        stock: 8,
        image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800',
        imageLarge: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=1200',
        imageHint: 'pearl earrings jewelry',
        brand: 'Pearl Co',
        gtin: '',
        mpn: '',
        category: 'Jewelry',
        condition: 'new',
        rating: 4.9,
        review_count: 67,
    },
];
