import { StyleSheet } from "react-native";
import { BRAND, RADIUS } from "@/constants/Colors";

const styles = StyleSheet.create({
  gridContainer: {
    borderRadius: RADIUS.xl,
    padding: 8,
    marginBottom: 16,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  imageWrapper: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: RADIUS.lg,
    overflow: "hidden",
    marginBottom: 10,
    position: "relative",
  },
  gridImage: { width: "100%", height: "100%" },
  imagePlaceholder: {
    justifyContent: "center",
    alignItems: "center",
  },
  badgeContainer: {
    position: "absolute",
    top: 8,
    left: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    zIndex: 10,
  },
  badgeText: {
    fontSize: 9,
    fontWeight: "800",
  },
  wishlistBtn: {
    position: "absolute",
    top: 4,
    right: 4,
    zIndex: 20,
    minWidth: 44,
    minHeight: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  wishlistBlur: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  floatingCartBtn: {
    position: "absolute",
    bottom: 4,
    right: 4,
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 20,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
  },
  gridContent: { paddingHorizontal: 4 },
  gridName: {
    fontSize: 13,
    fontFamily: "serif",
    marginBottom: 4,
    lineHeight: 18,
    fontWeight: "500",
  },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    paddingTop: 8,
  },
  gridPrice: { fontSize: 16, fontFamily: "serif", fontWeight: "bold" },
  detailsText: {
    fontSize: 11,
    fontFamily: "serif",
    fontWeight: "600",
  },
  ratingRowMini: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    marginBottom: 4,
  },
  ratingTextMini: {
    fontSize: 10,
    marginLeft: 4,
    fontWeight: "600",
  },
  listContainer: {
    flexDirection: "row",
    padding: 12,
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    gap: 16,
    alignItems: "center",
  },
  listImage: {
    width: 100,
    height: 100,
    borderRadius: RADIUS.lg,
  },
  listContent: {
    flex: 1,
  },
  listName: {
    fontSize: 16,
    fontFamily: "serif",
    fontWeight: "700",
    marginBottom: 4,
  },
  listDescription: {
    fontSize: 12,
    marginBottom: 8,
    lineHeight: 16,
  },
  listFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  listPrice: {
    fontSize: 18,
    fontFamily: "serif",
    fontWeight: "800",
  },
  listCartBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 6,
  },
  listCartLabel: {
    fontSize: 12,
    fontWeight: "800",
  },
  listWishlistBtn: {
    position: "absolute",
    top: 12,
    right: 12,
    padding: 4,
  },
  editorialContainer: {
    marginBottom: 24,
    marginHorizontal: 16,
  },
  editorialImage: { width: "100%", aspectRatio: 0.8, borderRadius: RADIUS.md },
  editorialContent: { marginTop: 12, alignItems: "center" },
  editorialName: {
    fontSize: 18,
    fontFamily: "serif",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  editorialPrice: { fontSize: 16, marginTop: 4, fontWeight: "500" },
  cartBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: BRAND.primary,
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    paddingHorizontal: 2,
  },
  listBadge: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: BRAND.primary,
    borderRadius: 7,
    minWidth: 14,
    height: 14,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
  },
  badgeTextMini: {
    fontSize: 8,
    fontWeight: "900",
    fontFamily: "Inter_900Black",
  },
});

export default styles;
