import type { MerchantAnalyticsResponse } from '@baci/shared';
import { isRuntimePlatform } from '@/config/runtime-platform';

// 2026 Best Practice: Dynamic imports for native modules to prevent evaluation-time crashes
let Print: typeof import('expo-print') | null = null;
let Sharing: typeof import('expo-sharing') | null = null;

const loadNativeModules = async () => {
  if (isRuntimePlatform('web')) return;
  try {
    const [prnt, shr] = await Promise.all([
      import('expo-print'),
      import('expo-sharing'),
    ]);
    Print = prnt;
    Sharing = shr;
  } catch (_e) {
    console.debug(
      '[ReportsGenerator] Native modules ignored or failed to load'
    );
  }
};

loadNativeModules();

import { formatCurrency } from '../../lib/utils';

/** Escape user-controlled strings to prevent XSS when interpolated into HTML */
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export type ReportType = 'executive' | 'tax_ledger';

export interface Transaction {
  id: string;
  created_at: string;
  total: number;
  tax_amount?: number;
  customer?: {
    first_name?: string;
    last_name?: string;
  };
}

interface ReportOptions {
  title: string;
  startDate: Date;
  endDate: Date;
  merchantName: string;
  /** ISO-4217 currency code resolved from merchant payout currency. */
  currency?: string;
  /** Optional locale override; defaults to the runtime/device locale. */
  locale?: string;
  data: MerchantAnalyticsResponse;
  transactions?: Transaction[]; // Full transaction list for Tax Ledger
}

const GLOBAL_STYLES = `
    body { font-family: 'Helvetica', 'Arial', sans-serif; padding: 40px; color: #333; }
    h1 { color: #111; font-size: 24px; margin-bottom: 4px; }
    h2 { font-size: 16px; color: #666; font-weight: normal; margin-top: 0; }
    .header { border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end; }
    .brand { font-size: 12px; color: #888; text-transform: uppercase; letter-spacing: 1px; }
    .footer { margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; font-size: 10px; color: #999; text-align: center; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th { text-align: left; background: #f9f9f9; padding: 10px; font-size: 12px; color: #555; border-bottom: 1px solid #ddd; }
    td { padding: 10px; font-size: 12px; border-bottom: 1px solid #eee; }
    .right { text-align: right; }
    .bold { font-weight: bold; }
    .kpi-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin-bottom: 40px; }
    .kpi-card { background: #f8f9fa; padding: 15px; border-radius: 8px; }
    .kpi-label { font-size: 11px; text-transform: uppercase; color: #666; margin-bottom: 5px; }
    .kpi-value { font-size: 18px; font-weight: bold; color: #000; }
`;

export async function generateReport(type: ReportType, options: ReportOptions) {
  const html =
    type === 'executive'
      ? getExecutiveSummaryHTML(options)
      : getTaxLedgerHTML(options);

  try {
    if (!Print || !Sharing) throw new Error('Native modules not loaded');
    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
  } catch (error) {
    console.error('Failed to generate report:', error);
    throw error;
  }
}

function getExecutiveSummaryHTML(options: ReportOptions) {
  const { title, startDate, endDate, merchantName, currency, locale, data } =
    options;
  const money = (amount: number) =>
    formatCurrency(amount, undefined, currency, locale);
  const period = `${startDate.toLocaleDateString(locale)} - ${endDate.toLocaleDateString(locale)}`;
  const safeMerchantName = escapeHtml(merchantName);
  const safeTitle = escapeHtml(title);
  const safeTopProduct = escapeHtml(data.topProducts?.[0]?.name || 'N/A');
  const safeTopBrand = escapeHtml(data.topBrand?.name || 'N/A');
  const safeTopCustomer = escapeHtml(data.topCustomer?.name || 'N/A');

  return `
        <html>
            <head>
                <style>${GLOBAL_STYLES}</style>
            </head>
            <body>
                <div class="header">
                    <div>
                        <h1>${safeMerchantName}</h1>
                        <h2>${safeTitle}</h2>
                    </div>
                    <div class="brand">Generated by Ogabassey</div>
                </div>

                <div class="kpi-grid">
                    <div class="kpi-card">
                        <div class="kpi-label">Total Revenue</div>
                        <div class="kpi-value">${money(data.summary?.revenue?.value ?? 0)}</div>
                    </div>
                    <div class="kpi-card">
                        <div class="kpi-label">Total Sales</div>
                        <div class="kpi-value">${data.summary?.sales?.value ?? 0}</div>
                    </div>
                    <div class="kpi-card">
                        <div class="kpi-label">Net Profit</div>
                        <div class="kpi-value">${money(data.summary?.profit?.value ?? 0)}</div>
                    </div>
                    <div class="kpi-card">
                        <div class="kpi-label">Avg Order Value</div>
                        <div class="kpi-value">${money(data.summary?.aov?.value ?? 0)}</div>
                    </div>
                </div>

                <h3>Top Performance</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Metric</th>
                            <th>Winner</th>
                            <th class="right">Value</th>
                        </tr>
                    </thead>
                    <tbody>
                         <tr>
                            <td>Top Product</td>
                            <td class="bold">${safeTopProduct}</td>
                            <td class="right">${money(data.topProducts?.[0]?.revenue || 0)}</td>
                        </tr>
                        <tr>
                            <td>Top Vendor</td>
                            <td class="bold">${safeTopBrand}</td>
                            <td class="right">${money(data.topBrand?.revenue || 0)}</td>
                        </tr>
                         <tr>
                            <td>Top Customer</td>
                            <td class="bold">${safeTopCustomer}</td>
                            <td class="right">${data.topCustomer?.value || 0} Orders</td>
                        </tr>
                    </tbody>
                </table>

                <div class="footer">
                    Report Period: ${period} • Generated on ${new Date().toLocaleString(locale)}
                </div>
            </body>
        </html>
    `;
}

function getTaxLedgerHTML(options: ReportOptions) {
  const {
    title,
    startDate,
    endDate,
    merchantName,
    currency,
    locale,
    data,
    transactions = [],
  } = options;
  const money = (amount: number) =>
    formatCurrency(amount, undefined, currency, locale);
  const period = `${startDate.toLocaleDateString(locale)} - ${endDate.toLocaleDateString(locale)}`;
  const safeMerchantName = escapeHtml(merchantName);
  const safeTitle = escapeHtml(title);

  // The backend contract says revenue is gross and taxDue <= revenue, but
  // refunds or data reconciliation bugs can produce a negative derived value;
  // clamp to zero so the report never shows nonsense taxable sales.
  const taxDueValue = data.summary?.taxDue?.value ?? 0;
  const revenueValue = data.summary?.revenue?.value ?? 0;
  const taxableSales = Math.max(0, revenueValue - taxDueValue);
  // Guard against division-by-zero and non-finite results: if there were no
  // taxable sales, we can't meaningfully express a rate, so fall back to
  // either a blank (no tax) or N/A (tax present without taxable sales).
  let taxRateLabel = '';
  if (taxableSales > 0) {
    const taxRatePct = (taxDueValue / taxableSales) * 100;
    if (Number.isFinite(taxRatePct) && taxRatePct > 0) {
      taxRateLabel = ` (${taxRatePct.toFixed(2)}%)`;
    }
  } else if (taxDueValue > 0) {
    taxRateLabel = ' (N/A)';
  }

  const rows = transactions
    .map(
      (tx) => `
        <tr>
            <td>${new Date(tx.created_at).toLocaleDateString(locale)}</td>
            <td>#${escapeHtml(tx.id.slice(0, 8))}</td>
            <td>${escapeHtml(tx.customer?.first_name || 'Guest')}</td>
            <td class="right">${money(tx.total - (tx.tax_amount || 0))}</td>
            <td class="right">${money(tx.tax_amount || 0)}</td>
            <td class="right bold">${money(tx.total)}</td>
        </tr>
    `
    )
    .join('');

  return `
        <html>
            <head>
                <style>${GLOBAL_STYLES}</style>
            </head>
            <body>
                <div class="header">
                    <div>
                        <h1>${safeMerchantName}</h1>
                        <h2>${safeTitle}</h2>
                    </div>
                    <div class="brand">Generated by Ogabassey</div>
                </div>

                <div class="kpi-grid" style="grid-template-columns: repeat(2, 1fr);">
                    <div class="kpi-card">
                        <div class="kpi-label">Total Taxable Sales</div>
                        <div class="kpi-value">${money(taxableSales)}</div>
                    </div>
                    <div class="kpi-card">
                        <div class="kpi-label">Tax Collected${taxRateLabel}</div>
                        <div class="kpi-value">${money(taxDueValue)}</div>
                    </div>
                </div>

                <h3>Transaction Ledger</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Order ID</th>
                            <th>Customer</th>
                            <th class="right">Subtotal</th>
                            <th class="right">Tax</th>
                            <th class="right">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${rows}
                    </tbody>
                </table>

                <div class="footer">
                    Report Period: ${period} • Generated on ${new Date().toLocaleString(locale)}
                </div>
            </body>
        </html>
    `;
}
