import type { Product } from '@/types/product';

export const baseProduct: Product = {
  id: 'product-1',
  merchant_id: 'merchant-1',
  name: 'iPhone 13 Pro',
  slug: 'iphone-13-pro',
  price: 552000,
  image: 'https://cdn.example.com/iphone-13-pro.jpg',
  images: ['https://cdn.example.com/iphone-13-pro.jpg'],
};

export const variantProduct: Product = {
  ...baseProduct,
  has_variants: true,
  variant_attributes: {
    storage: ['128GB'],
    connectivity: ['WiFi'],
  },
  variants: [
    {
      id: 'variant-new-128',
      name: '128GB WiFi',
      condition: 'new',
      price: 552000,
      stock_quantity: 5,
      attributes: {
        storage: '128GB',
        connectivity: 'WiFi',
      },
    },
    {
      id: 'variant-used-128',
      name: '128GB WiFi Used',
      condition: 'used',
      price: 500000,
      stock_quantity: 3,
      attributes: {
        storage: '128GB',
        connectivity: 'WiFi',
      },
    },
  ],
};

const variantFixtures = variantProduct.variants ?? [];

if (variantFixtures.length < 2) {
  throw new Error('variantProduct must include at least two variants');
}

export const [primaryVariant, secondaryVariant] = variantFixtures as [
  (typeof variantFixtures)[number],
  (typeof variantFixtures)[number],
];

export function iphone11ProMax(): Product {
  return {
    id: 'iphone-11-pro-max',
    merchant_id: 'm-1',
    name: 'iPhone 11 Pro Max',
    slug: 'iphone-11-pro-max',
    price: 520000,
    image: 'https://cdn.example.com/i11pm.jpg',
    images: [
      'https://cdn.example.com/i11pm-midnight-green.jpg',
      'https://cdn.example.com/i11pm-silver.jpg',
      'https://cdn.example.com/i11pm-space-gray.jpg',
      'https://cdn.example.com/i11pm-gold.jpg',
    ],
    condition: 'Open Box',
    has_variants: true,
    manage_stock: false,
    stock_quantity: 0,
    variant_attributes: { storage: ['64GB', '256GB', '512GB'] },
    color_images: {},
    colors: ['Midnight Green', 'Silver', 'Space Gray', 'Gold'],
    offers: [],
    variants: [
      {
        id: 'ob-midnight-green-64',
        name: 'Open Box Midnight Green 64GB',
        condition: 'open_box',
        stock_quantity: 0,
        price: 520000,
        price_override: 520000,
        image: 'https://cdn.example.com/i11pm-midnight-green.jpg',
        images: ['https://cdn.example.com/i11pm-midnight-green.jpg'],
        attributes: {
          color: 'Midnight Green',
          storage: '64GB',
          color_hex: '#4F5C53',
        },
      },
      {
        id: 'ob-midnight-green-256',
        name: 'Open Box Midnight Green 256GB',
        condition: 'open_box',
        stock_quantity: 0,
        price: 600000,
        price_override: 600000,
        image: 'https://cdn.example.com/i11pm-midnight-green.jpg',
        images: ['https://cdn.example.com/i11pm-midnight-green.jpg'],
        attributes: {
          color: 'Midnight Green',
          storage: '256GB',
          color_hex: '#4F5C53',
        },
      },
      {
        id: 'ob-midnight-green-512',
        name: 'Open Box Midnight Green 512GB',
        condition: 'open_box',
        stock_quantity: 0,
        price: 700000,
        price_override: 700000,
        image: 'https://cdn.example.com/i11pm-midnight-green.jpg',
        images: ['https://cdn.example.com/i11pm-midnight-green.jpg'],
        attributes: {
          color: 'Midnight Green',
          storage: '512GB',
          color_hex: '#4F5C53',
        },
      },
      {
        id: 'used-midnight-green-64',
        name: 'Used Midnight Green 64GB',
        condition: 'used',
        stock_quantity: 0,
        price: 470000,
        price_override: 470000,
        image: 'https://cdn.example.com/i11pm-midnight-green.jpg',
        images: ['https://cdn.example.com/i11pm-midnight-green.jpg'],
        attributes: {
          color: 'Midnight Green',
          storage: '64GB',
          color_hex: '#4F5C53',
        },
      },
      {
        id: 'used-midnight-green-256',
        name: 'Used Midnight Green 256GB',
        condition: 'used',
        stock_quantity: 0,
        price: 550000,
        price_override: 550000,
        image: 'https://cdn.example.com/i11pm-midnight-green.jpg',
        images: ['https://cdn.example.com/i11pm-midnight-green.jpg'],
        attributes: {
          color: 'Midnight Green',
          storage: '256GB',
          color_hex: '#4F5C53',
        },
      },
      {
        id: 'used-midnight-green-512',
        name: 'Used Midnight Green 512GB',
        condition: 'used',
        stock_quantity: 0,
        price: 650000,
        price_override: 650000,
        image: 'https://cdn.example.com/i11pm-midnight-green.jpg',
        images: ['https://cdn.example.com/i11pm-midnight-green.jpg'],
        attributes: {
          color: 'Midnight Green',
          storage: '512GB',
          color_hex: '#4F5C53',
        },
      },
      {
        id: 'used-gold-64',
        name: 'Used Gold 64GB',
        condition: 'used',
        stock_quantity: 0,
        price: 470000,
        price_override: 470000,
        image: 'https://cdn.example.com/i11pm-gold.jpg',
        images: ['https://cdn.example.com/i11pm-gold.jpg'],
        attributes: { color: 'Gold', storage: '64GB', color_hex: '#F5D4A3' },
      },
      {
        id: 'ob-gold-64',
        name: 'Open Box Gold 64GB',
        condition: 'open_box',
        stock_quantity: 0,
        price: 520000,
        price_override: 520000,
        image: 'https://cdn.example.com/i11pm-gold.jpg',
        images: ['https://cdn.example.com/i11pm-gold.jpg'],
        attributes: { color: 'Gold', storage: '64GB', color_hex: '#F5D4A3' },
      },
      {
        id: 'used-gold-256',
        name: 'Used Gold 256GB',
        condition: 'used',
        stock_quantity: 0,
        price: 550000,
        price_override: 550000,
        image: 'https://cdn.example.com/i11pm-gold.jpg',
        images: ['https://cdn.example.com/i11pm-gold.jpg'],
        attributes: { color: 'Gold', storage: '256GB', color_hex: '#F5D4A3' },
      },
      {
        id: 'ob-gold-256',
        name: 'Open Box Gold 256GB',
        condition: 'open_box',
        stock_quantity: 0,
        price: 600000,
        price_override: 600000,
        image: 'https://cdn.example.com/i11pm-gold.jpg',
        images: ['https://cdn.example.com/i11pm-gold.jpg'],
        attributes: { color: 'Gold', storage: '256GB', color_hex: '#F5D4A3' },
      },
      {
        id: 'used-gold-512',
        name: 'Used Gold 512GB',
        condition: 'used',
        stock_quantity: 0,
        price: 650000,
        price_override: 650000,
        image: 'https://cdn.example.com/i11pm-gold.jpg',
        images: ['https://cdn.example.com/i11pm-gold.jpg'],
        attributes: { color: 'Gold', storage: '512GB', color_hex: '#F5D4A3' },
      },
      {
        id: 'ob-gold-512',
        name: 'Open Box Gold 512GB',
        condition: 'open_box',
        stock_quantity: 0,
        price: 700000,
        price_override: 700000,
        image: 'https://cdn.example.com/i11pm-gold.jpg',
        images: ['https://cdn.example.com/i11pm-gold.jpg'],
        attributes: { color: 'Gold', storage: '512GB', color_hex: '#F5D4A3' },
      },
      {
        id: 'used-space-gray-64',
        name: 'Used Space Gray 64GB',
        condition: 'used',
        stock_quantity: 0,
        price: 470000,
        price_override: 470000,
        image: 'https://cdn.example.com/i11pm-space-gray.jpg',
        images: ['https://cdn.example.com/i11pm-space-gray.jpg'],
        attributes: {
          color: 'Space Gray',
          storage: '64GB',
          color_hex: '#54524F',
        },
      },
      {
        id: 'used-silver-64',
        name: 'Used Silver 64GB',
        condition: 'used',
        stock_quantity: 0,
        price: 470000,
        price_override: 470000,
        image: 'https://cdn.example.com/i11pm-silver.jpg',
        images: ['https://cdn.example.com/i11pm-silver.jpg'],
        attributes: { color: 'Silver', storage: '64GB', color_hex: '#E5E5E5' },
      },
    ],
  };
}
