import { existsSync, readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it, jest } from '@jest/globals';
import type { ConfigContext, ExpoConfig } from 'expo/config';

type AppConfig = typeof import('../../app.config').default;

const ROOT = path.resolve(__dirname, '../..');
const EXCLUDED_SOURCE_DIRECTORIES = new Set(['__tests__', 'test-utils']);

function findTypeScriptSourceFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const entryPath = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      if (EXCLUDED_SOURCE_DIRECTORIES.has(entry.name)) {
        return [];
      }

      return findTypeScriptSourceFiles(entryPath);
    }

    if (
      !/\.(ts|tsx)$/.test(entry.name) ||
      entry.name.includes('.test.') ||
      entry.name.includes('.test-utils.')
    ) {
      return [];
    }

    return [entryPath];
  });
}

describe('Expo compliance', () => {
  it('uses a manual runtime version for bare workflow builds', () => {
    const originalFacebookAppId = process.env.STOREFRONT_FACEBOOK_APP_ID;
    const originalFacebookClientToken =
      process.env.STOREFRONT_FACEBOOK_CLIENT_TOKEN;
    const originalPosthogApiKey = process.env.EXPO_PUBLIC_POSTHOG_API_KEY;

    process.env.STOREFRONT_FACEBOOK_APP_ID = '123456789';
    process.env.STOREFRONT_FACEBOOK_CLIENT_TOKEN = 'client-token';
    process.env.EXPO_PUBLIC_POSTHOG_API_KEY = 'ph_test';

    try {
      let config: ExpoConfig | undefined;

      jest.isolateModules(() => {
        const appConfig = require('../../app.config').default as AppConfig;
        const configContext: ConfigContext = {
          config: {} as ExpoConfig,
          packageJsonPath: '',
          projectRoot: ROOT,
          staticConfigPath: '',
        };

        config = appConfig(configContext);
      });

      if (!config) {
        throw new Error('Expected app config to render');
      }

      expect(typeof config.runtimeVersion).toBe('string');
      expect(config.runtimeVersion).toBe(config.version);
    } finally {
      if (originalFacebookAppId === undefined) {
        delete process.env.STOREFRONT_FACEBOOK_APP_ID;
      } else {
        process.env.STOREFRONT_FACEBOOK_APP_ID = originalFacebookAppId;
      }

      if (originalFacebookClientToken === undefined) {
        delete process.env.STOREFRONT_FACEBOOK_CLIENT_TOKEN;
      } else {
        process.env.STOREFRONT_FACEBOOK_CLIENT_TOKEN =
          originalFacebookClientToken;
      }

      if (originalPosthogApiKey === undefined) {
        delete process.env.EXPO_PUBLIC_POSTHOG_API_KEY;
      } else {
        process.env.EXPO_PUBLIC_POSTHOG_API_KEY = originalPosthogApiKey;
      }
    }
  });

  it('app.config.ts does not contain an explicit newArchEnabled override', () => {
    const configSource = readFileSync(
      path.join(ROOT, 'app.config.ts'),
      'utf-8'
    );
    expect(configSource).not.toContain('newArchEnabled');
  });

  it('sets the supported iOS deployment target to 16.4', () => {
    const configSource = readFileSync(
      path.join(ROOT, 'app.config.ts'),
      'utf-8'
    );

    expect(configSource).toContain("deploymentTarget: '16.4'");
    expect(configSource).not.toContain("deploymentTarget: '15.1'");
  });

  it('configures the Expo splash plugin without a static splash image', () => {
    const configSource = readFileSync(
      path.join(ROOT, 'app.config.ts'),
      'utf-8'
    );

    expect(configSource).toContain("'expo-splash-screen'");
    expect(configSource).toContain("backgroundColor: '#000000'");
    expect(configSource).not.toContain(
      "image: './assets/images/splash-icon.png'"
    );
    expect(configSource).not.toContain("resizeMode: 'contain'");
    expect(configSource).toContain("'./config/withNoSplashImage.js'");
  });

  it('gradle.properties does not contain newArchEnabled', () => {
    const filePath = path.join(ROOT, 'android/gradle.properties');
    if (!existsSync(filePath)) return; // generated by prebuild, gitignored
    const gradleProps = readFileSync(filePath, 'utf-8');
    const sourceLines = gradleProps
      .split('\n')
      .filter((l) => !l.startsWith('newArchEnabled'));
    expect(sourceLines.join('\n')).not.toContain('newArchEnabled');
  });

  it('Podfile.properties.json does not contain newArchEnabled', () => {
    const filePath = path.join(ROOT, 'ios/Podfile.properties.json');
    if (!existsSync(filePath)) return; // generated by prebuild, gitignored
    const podfileProps = readFileSync(filePath, 'utf-8');
    expect(podfileProps).not.toContain('newArchEnabled');
  });

  it('uses style.pointerEvents instead of deprecated JSX pointerEvents props', () => {
    const offenders = ['app', 'components', 'hooks']
      .flatMap((sourceDirectory) =>
        findTypeScriptSourceFiles(path.join(ROOT, sourceDirectory))
      )
      .filter((filePath) =>
        /\bpointerEvents\s*=/.test(readFileSync(filePath, 'utf-8'))
      )
      .map((filePath) => path.relative(ROOT, filePath));

    expect(offenders).toEqual([]);
  });
});
