import { existsSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import appConfig from '../../app.config';

const ROOT = path.resolve(__dirname, '../..');
const EXCLUDED_SOURCE_DIRECTORIES = new Set(['__tests__', 'test-utils']);

function findTypeScriptSourceFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const entryPath = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      if (EXCLUDED_SOURCE_DIRECTORIES.has(entry.name)) {
        return [];
      }

      return findTypeScriptSourceFiles(entryPath);
    }

    if (
      !/\.(ts|tsx)$/.test(entry.name) ||
      entry.name.includes('.test.') ||
      entry.name.includes('.test-utils.')
    ) {
      return [];
    }

    return [entryPath];
  });
}

describe('SDK 56 compliance', () => {
  it('uses a manual runtime version for bare workflow builds', () => {
    const config = appConfig({ config: {} as never } as unknown as Parameters<
      typeof appConfig
    >[0]);

    expect(typeof config.runtimeVersion).toBe('string');
    expect(config.runtimeVersion).toBe(config.version);
  });

  it('app.config.ts does not contain an explicit newArchEnabled override', () => {
    const configSource = readFileSync(
      path.join(ROOT, 'app.config.ts'),
      'utf-8'
    );
    expect(configSource).not.toContain('newArchEnabled');
  });

  it('sets SDK 56 iOS deployment target to 16.4', () => {
    const configSource = readFileSync(
      path.join(ROOT, 'app.config.ts'),
      'utf-8'
    );

    expect(configSource).toContain("deploymentTarget: '16.4'");
    expect(configSource).not.toContain("deploymentTarget: '15.1'");
  });

  it('configures the SDK 56 splash plugin with an Android drawable source', () => {
    const configSource = readFileSync(
      path.join(ROOT, 'app.config.ts'),
      'utf-8'
    );

    expect(configSource).toContain("'expo-splash-screen'");
    expect(configSource).toContain("image: './assets/images/splash-icon.png'");
    expect(configSource).toContain("resizeMode: 'contain'");
    expect(configSource).toContain("backgroundColor: '#000000'");
  });

  it('gradle.properties does not contain newArchEnabled', () => {
    const filePath = path.join(ROOT, 'android/gradle.properties');
    if (!existsSync(filePath)) return; // generated by prebuild, gitignored
    const gradleProps = readFileSync(filePath, 'utf-8');
    const sourceLines = gradleProps
      .split('\n')
      .filter((l) => !l.startsWith('newArchEnabled'));
    expect(sourceLines.join('\n')).not.toContain('newArchEnabled');
  });

  it('Podfile.properties.json does not contain newArchEnabled', () => {
    const filePath = path.join(ROOT, 'ios/Podfile.properties.json');
    if (!existsSync(filePath)) return; // generated by prebuild, gitignored
    const podfileProps = readFileSync(filePath, 'utf-8');
    expect(podfileProps).not.toContain('newArchEnabled');
  });

  it('uses style.pointerEvents instead of deprecated JSX pointerEvents props', () => {
    const offenders = ['app', 'components', 'hooks']
      .flatMap((sourceDirectory) =>
        findTypeScriptSourceFiles(path.join(ROOT, sourceDirectory))
      )
      .filter((filePath) =>
        /\bpointerEvents\s*=/.test(readFileSync(filePath, 'utf-8'))
      )
      .map((filePath) => path.relative(ROOT, filePath));

    expect(offenders).toEqual([]);
  });
});
