import { existsSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import appConfig from '../../app.config';

const ROOT = path.resolve(__dirname, '../..');

function findTypeScriptSourceFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const entryPath = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      return findTypeScriptSourceFiles(entryPath);
    }

    if (
      !/\.(ts|tsx)$/.test(entry.name) ||
      entry.name.includes('.test.') ||
      entry.name.includes('.test-utils.')
    ) {
      return [];
    }

    return [entryPath];
  });
}

describe('SDK 55 compliance', () => {
  it('uses a manual runtime version for bare workflow builds', () => {
    const config = appConfig({ config: {} as never } as unknown as Parameters<
      typeof appConfig
    >[0]);

    expect(typeof config.runtimeVersion).toBe('string');
    expect(config.runtimeVersion).toBe(config.version);
  });

  it('app.config.ts does not contain newArchEnabled (removed in SDK 55)', () => {
    const configSource = readFileSync(
      path.join(ROOT, 'app.config.ts'),
      'utf-8'
    );
    expect(configSource).not.toContain('newArchEnabled');
  });

  it('gradle.properties does not contain newArchEnabled', () => {
    const filePath = path.join(ROOT, 'android/gradle.properties');
    if (!existsSync(filePath)) return; // generated by prebuild, gitignored
    const gradleProps = readFileSync(filePath, 'utf-8');
    const sourceLines = gradleProps
      .split('\n')
      .filter((l) => !l.startsWith('newArchEnabled'));
    expect(sourceLines.join('\n')).not.toContain('newArchEnabled');
  });

  it('Podfile.properties.json does not contain newArchEnabled', () => {
    const filePath = path.join(ROOT, 'ios/Podfile.properties.json');
    if (!existsSync(filePath)) return; // generated by prebuild, gitignored
    const podfileProps = readFileSync(filePath, 'utf-8');
    expect(podfileProps).not.toContain('newArchEnabled');
  });

  it('uses style.pointerEvents instead of deprecated JSX pointerEvents props', () => {
    const offenders = ['app', 'components', 'hooks']
      .flatMap((sourceDirectory) =>
        findTypeScriptSourceFiles(path.join(ROOT, sourceDirectory))
      )
      .filter((filePath) =>
        /\bpointerEvents\s*=/.test(readFileSync(filePath, 'utf-8'))
      )
      .map((filePath) => path.relative(ROOT, filePath));

    expect(offenders).toEqual([]);
  });
});
