import { StyleSheet } from 'react-native';
import { BRAND, palette, SHADOWS } from '@/constants/Colors';

export const negotiationModalViewStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.65)',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  modalContainer: {
    width: '90%',
    maxWidth: 390,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#FFF',
    ...SHADOWS.lg,
  },
  header: {
    backgroundColor: '#1A1A1A',
    paddingVertical: 16,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1,
  },
  closeButton: {
    padding: 4,
  },
  content: {
    maxHeight: 540,
  },
  contentContainer: {
    padding: 24,
  },
  productInfo: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    backgroundColor: '#F9FAFB',
  },
  productLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: palette.gray[500],
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  productName: {
    fontSize: 14,
    fontWeight: '600',
    color: palette.gray[900],
    marginBottom: 6,
  },
  priceRow: { fontSize: 13 },
  priceLabel: { color: palette.gray[600] },
  priceValue: { color: '#111827', fontWeight: '700' },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 10,
  },
  inputContainer: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 14,
  },
  priceInput: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  submitButton: {
    backgroundColor: BRAND.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  submitButtonText: { color: '#FFF', fontWeight: '700', fontSize: 15 },
  centerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
  },
  processingText: {
    marginTop: 10,
    color: '#374151',
    fontWeight: '600',
  },
  successCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#DCFCE7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  amberCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FEF3C7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  successTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  successSubtext: {
    fontSize: 14,
    color: '#4B5563',
    textAlign: 'center',
    marginBottom: 16,
  },
  applyButton: {
    backgroundColor: '#16A34A',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
  },
  applyButtonText: {
    color: '#FFF',
    fontWeight: '700',
    fontSize: 15,
  },
  doneButton: {
    backgroundColor: '#111827',
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: 10,
  },
  doneButtonText: {
    color: '#FFF',
    fontWeight: '700',
    fontSize: 14,
  },
  counterBox: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#FBBF24',
    backgroundColor: '#FFFBEB',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    marginBottom: 14,
  },
  counterPrice: {
    fontSize: 20,
    fontWeight: '700',
    color: '#92400E',
    marginBottom: 10,
  },
  acceptButton: {
    backgroundColor: '#16A34A',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  acceptButtonText: { color: '#FFF', fontWeight: '700' },
  failedActions: { width: '100%', gap: 8 },
  tryAgainButton: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  tryAgainButtonText: { color: '#111827', fontWeight: '600' },
  cheaperButton: {
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    backgroundColor: '#EFF6FF',
  },
  cheaperButtonText: { color: '#1D4ED8', fontWeight: '700' },
  uploadHelp: { color: '#4B5563', marginBottom: 12 },
  uploadInfoBox: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  uploadInfoText: { color: '#1E40AF', fontSize: 13 },
  uploadButton: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
    backgroundColor: '#FFF',
  },
  uploadButtonText: { color: '#111827', fontWeight: '600' },
  selectedFileText: { color: '#166534', fontSize: 12, marginBottom: 8 },
  orText: { textAlign: 'center', color: '#6B7280', marginVertical: 8 },
  linkInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#111827',
    marginBottom: 12,
  },
  uploadActions: { flexDirection: 'row', gap: 8 },
  backButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  backButtonText: { color: '#111827', fontWeight: '600' },
  sendReviewButton: {
    flex: 1.3,
    backgroundColor: '#1D4ED8',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  sendReviewButtonText: { color: '#FFF', fontWeight: '700' },
});
