import { StyleSheet } from 'react-native';

export const negotiationModalViewStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.65)',
  },
  backdrop: {
    ...StyleSheet.absoluteFill,
  },
  modalContainer: {
    width: '90%',
    maxWidth: 400,
    borderRadius: 24,
    overflow: 'hidden',
  },
  header: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerIcon: {
    width: 28,
    height: 28,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  closeButton: {
    padding: 4,
  },
  content: {
    maxHeight: 540,
  },
  contentContainer: {
    padding: 24,
  },
  productInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    marginBottom: 20,
  },
  productInfoText: {
    flex: 1,
  },
  productPriceColumn: {
    alignItems: 'flex-end',
  },
  productLabel: {
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 4,
    letterSpacing: 0.6,
  },
  productName: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 19,
  },
  priceLabel: { fontSize: 11, marginBottom: 2 },
  priceValue: { fontSize: 16, fontWeight: '700' },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 10,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 8,
  },
  currencyPrefix: {
    fontSize: 22,
    fontWeight: '700',
  },
  priceInput: {
    flex: 1,
    fontSize: 26,
    fontWeight: '700',
    padding: 0,
  },
  inputHint: {
    fontSize: 12,
    marginBottom: 18,
    lineHeight: 16,
  },
  submitButton: {
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
  },
  submitButtonText: { fontWeight: '700', fontSize: 15 },
  centerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
  },
  processingText: {
    marginTop: 10,
    fontWeight: '600',
  },
  statusCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  successTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 8,
  },
  successSubtext: {
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 18,
    lineHeight: 20,
  },
  applyButton: {
    paddingVertical: 13,
    paddingHorizontal: 28,
    borderRadius: 14,
  },
  applyButtonText: {
    fontWeight: '700',
    fontSize: 15,
  },
  doneButton: {
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 12,
  },
  doneButtonText: {
    fontWeight: '700',
    fontSize: 14,
  },
  counterBox: {
    width: '100%',
    borderWidth: 1,
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    marginBottom: 16,
  },
  counterPrice: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 12,
  },
  acceptButton: {
    borderRadius: 12,
    paddingVertical: 11,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  acceptButtonText: { color: '#FFF', fontWeight: '700' },
  failedActions: { width: '100%', gap: 10 },
  tryAgainButton: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  tryAgainButtonText: { fontWeight: '600' },
  cheaperButton: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  cheaperButtonText: { fontWeight: '700' },
  uploadHelp: { color: '#4B5563', marginBottom: 12 },
  uploadInfoBox: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  uploadInfoText: { color: '#1E40AF', fontSize: 13 },
  uploadButton: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
    backgroundColor: '#FFF',
  },
  uploadButtonText: { color: '#111827', fontWeight: '600' },
  selectedFileText: { color: '#166534', fontSize: 12, marginBottom: 8 },
  orText: { textAlign: 'center', color: '#6B7280', marginVertical: 8 },
  linkInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#111827',
    marginBottom: 12,
  },
  uploadActions: { flexDirection: 'row', gap: 8 },
  backButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  backButtonText: { color: '#111827', fontWeight: '600' },
  sendReviewButton: {
    flex: 1.3,
    backgroundColor: '#1D4ED8',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  sendReviewButtonText: { color: '#FFF', fontWeight: '700' },
});
