import { describe, expect, it } from 'vitest';
import {
  SUPABASE_REPLAY_PORT_KEYS,
  type SupabaseReplayPortMap,
} from './allocate-supabase-replay-ports';
import {
  parseSupabaseReplayConfig,
  rewriteSupabaseReplayConfig,
} from './rewrite-supabase-replay-config';

const config = `project_id = "supabase"

[api]
enabled = true
port = 54321

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.pooler]
enabled = false
port = 54329

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true

[storage.image_transformation]
enabled = true

[storage.s3_protocol]
enabled = true

[edge_runtime]
enabled = true
inspector_port = 8083

[analytics]
enabled = true
port = 54327
`;

const ports = Object.fromEntries(
  SUPABASE_REPLAY_PORT_KEYS.map((key, index) => [key, 41_000 + index])
) as SupabaseReplayPortMap;

describe('rewriteSupabaseReplayConfig', () => {
  it('rewrites only project identity and the seven qualified ports', () => {
    const rewritten = rewriteSupabaseReplayConfig(config, {
      ports,
      projectId: 'baci_replay_abc123',
    });
    const parsed = parseSupabaseReplayConfig(rewritten);

    expect(parsed).toMatchObject({
      dbMajorVersion: 17,
      imageTransformationEnabled: true,
      poolerEnabled: false,
      ports,
      projectId: 'baci_replay_abc123',
    });
    expect(rewritten).toContain('# smtp_port = 54325');
    expect(rewritten).toContain('[storage.s3_protocol]\nenabled = true');
    expect(rewritten).toContain('[db.pooler]\nenabled = false\nport = 54329');
  });

  it('permits repeated bare port keys only across qualified sections', () => {
    expect(parseSupabaseReplayConfig(config).ports).toEqual({
      'analytics.port': 54327,
      'api.port': 54321,
      'db.port': 54322,
      'db.shadow_port': 54320,
      'edge_runtime.inspector_port': 8083,
      'inbucket.port': 54324,
      'studio.port': 54323,
    });
  });

  it('rewrites a mixed-case project id generated by Supabase init', () => {
    const generatedConfig = config.replace(
      'project_id = "supabase"',
      'project_id = "baci-supabase-replay-AbC123"'
    );

    const rewritten = rewriteSupabaseReplayConfig(generatedConfig, {
      ports,
      projectId: 'baci_replay_abc123',
    });

    expect(parseSupabaseReplayConfig(rewritten).projectId).toBe(
      'baci_replay_abc123'
    );
  });

  it.each([
    [
      'duplicate qualified port',
      config.replace('port = 54322', 'port = 54322\nport = 55555'),
    ],
    [
      'enabled pooler port',
      config.replace(
        '[db.pooler]\nenabled = false',
        '[db.pooler]\nenabled = true'
      ),
    ],
    [
      'unknown enabled port',
      `${config}\n[unknown]\nenabled = true\nport = 59999\n`,
    ],
    ['nonnumeric port', config.replace('port = 54321', 'port = "54321"')],
    ['missing expected port', config.replace('inspector_port = 8083\n', '')],
    [
      'wrong database major',
      config.replace('major_version = 17', 'major_version = 16'),
    ],
  ])('rejects %s with a sanitized structural error', (_name, candidate) => {
    expect(() => parseSupabaseReplayConfig(candidate)).toThrow(
      /^Invalid Supabase replay config$/
    );
  });

  it('rejects a rewrite that leaves any generated default port in place', () => {
    expect(() =>
      rewriteSupabaseReplayConfig(config, {
        ports: { ...ports, 'api.port': 54321 },
        projectId: 'baci_replay_abc123',
      })
    ).toThrow(/^Invalid Supabase replay config rewrite$/);
  });
});
