import { calculateStorefrontDeliveryDailyEvidenceSha256 } from './delivery-evidence';

export const dailyEvidence = {
  utcDate: '2026-07-01',
  hostnameInventorySha256: 'a'.repeat(64),
  eligibilityPolicySha256: 'b'.repeat(64),
  aliasRulesetVersion: 'alias-v1',
  wafRulesetVersion: 'waf-v1',
  responseHeaderRulesetSha256: 'c'.repeat(64),
  rawOriginRobotsTxtSha256: 'd'.repeat(64),
  workerDeploymentId: 'deployment-v1',
  originOnlyVersionId: 'origin-v1',
  edgeVersionId: 'edge-v1',
  source: 'worker-analytics',
  exportedAt: '2026-07-02T00:00:00.000Z',
  providerSamplingApplied: false,
  maxSampleInterval: 1,
  exportComplete: true,
  invocationCountExact: true,
  workerInvocationCount: 1000,
  totalDecisionCount: 1000,
  syntheticQualificationRequestCount: 0,
  canonicalEligibleRequestCount: 1000,
  canonicalEligibleOriginAttemptCount: 0,
  dynamicOriginAttemptCount: 0,
  unknownOriginAttemptCount: 0,
  edgeReleaseCount: 1000,
  edgeRejectCount: 0,
  originFallbackCount: 0,
  terminalCount: 0,
  edgeErrorCount: 0,
  aliasRawRequestCount: 0,
  aliasEligibleRequestCount: 0,
  aliasEdgeRedirectCount: 0,
  aliasEligibleOriginRequestCount: 0,
  aliasDynamicOriginCount: 0,
  rejectedMethodRequestCount: 0,
  rejectedMethodOriginCount: 0,
  allowedOriginRateLimitCount: 0,
  trafficPartition: [
    {
      hostname: 'ogabassey.com',
      methodClass: 'GET_HEAD',
      pathClass: 'document',
      ruleId: 'worker-static',
      requestCount: 1000,
      eligibleRequestCount: 1000,
      eligibleOriginAttemptCount: 0,
    },
    {
      hostname: 'ogabassey.usebaci.com',
      methodClass: 'GET_HEAD',
      pathClass: 'document',
      ruleId: 'alias-static',
      requestCount: 0,
      eligibleRequestCount: 0,
      eligibleOriginAttemptCount: 0,
    },
    {
      hostname: 'www.ogabassey.com',
      methodClass: 'GET_HEAD',
      pathClass: 'document',
      ruleId: 'alias-static',
      requestCount: 0,
      eligibleRequestCount: 0,
      eligibleOriginAttemptCount: 0,
    },
  ],
  sourceEvidence: {
    invocation: {
      sourceFingerprint: 'invocation-v1',
      requestCount: 1000,
      complete: true,
      exact: true,
      providerSamplingApplied: false,
      maxSampleInterval: 1,
    },
    aliasRedirect: {
      sourceFingerprint: 'alias-v1',
      hostPartition: [
        {
          hostname: 'ogabassey.usebaci.com',
          requestCount: 0,
          eligibleRequestCount: 0,
          eligibleOriginAttemptCount: 0,
        },
        {
          hostname: 'www.ogabassey.com',
          requestCount: 0,
          eligibleRequestCount: 0,
          eligibleOriginAttemptCount: 0,
        },
      ],
      complete: true,
      exact: true,
      providerSamplingApplied: false,
      maxSampleInterval: 1,
    },
    wafRateLimit: {
      sourceFingerprint: 'waf-v1',
      rejectedMethodRequestCount: 0,
      rejectedMethodOriginCount: 0,
      allowedOriginRateLimitCount: 0,
      complete: true,
      exact: true,
      providerSamplingApplied: false,
      maxSampleInterval: 1,
    },
    originEvent: {
      sourceFingerprint: 'origin-v1',
      requestCount: 0,
      complete: true,
      exact: true,
      providerSamplingApplied: false,
      maxSampleInterval: 1,
    },
    syntheticQualification: {
      sourceFingerprint: 'synthetic-v1',
      requestCount: 0,
      complete: true,
      exact: true,
      providerSamplingApplied: false,
      maxSampleInterval: 1,
    },
  },
  sha256: '',
};

dailyEvidence.sha256 =
  calculateStorefrontDeliveryDailyEvidenceSha256(dailyEvidence);
