import { STOREFRONT_EDGE_MACHINE_SOURCE_PATHS } from './storefront-edge-machine-source-paths';
import {
  STOREFRONT_EDGE_PLATFORM_ROOT_FAVICON_ROW,
  STOREFRONT_EDGE_PUBLIC_ASSET_ROWS,
} from './storefront-edge-public-asset-rows';
import { STOREFRONT_EDGE_ROUTING_INPUT_PATHS } from './storefront-edge-routing-input-paths';

/** Reviewed routing-input bytes hashed into the Task 1A inventory authority. */
export const STOREFRONT_EDGE_INVENTORY_ROUTING_INPUT_PATHS = [
  ...STOREFRONT_EDGE_ROUTING_INPUT_PATHS,
  'apps/web/next.config.ts',
  'apps/web/src/app/actions/repair.ts',
  'apps/web/src/app/auth/confirm/route.ts',
  'apps/web/src/app/agent/auth/route.ts',
  'apps/web/src/app/agent/auth/[action]/route.ts',
  'apps/web/src/app/layout.tsx',
  'apps/web/src/app/root-dynamic-body.tsx',
  'apps/web/src/app/sitemap.ts',
  'apps/web/src/proxy.ts',
  'apps/web/src/components/analytics/deferred-platform-insights.tsx',
  'apps/web/src/components/analytics/posthog-client-bootstrap.tsx',
  'apps/web/src/components/analytics/posthog-pageview-tracker.tsx',
  'apps/web/src/components/analytics/web-vitals-reporter.tsx',
  'apps/web/src/components/storefront/ad-attribution-capture.tsx',
  'apps/web/src/components/storefront/deferred-page-view-tracker.tsx',
  'apps/web/src/components/storefront/puck-storefront.tsx',
  'apps/web/src/components/storefront/cdn-format-image.tsx',
  'apps/web/src/components/storefront/ogabassey/pages/about-us.tsx',
  'apps/web/src/components/storefront/ogabassey/pages/privacy-policy.tsx',
  'apps/web/src/components/storefront/ogabassey/pages/legal-dispute.tsx',
  'apps/web/src/components/storefront/ogabassey/pages/sustainability.tsx',
  'apps/web/src/components/storefront/ogabassey/pages/swap.tsx',
  'apps/web/src/components/storefront/ogabassey/pages/crypto-checkout.tsx',
  'apps/web/src/components/storefront/ogabassey/components/ProductVideo.tsx',
  'apps/web/src/components/storefront/ogabassey/components/PaymentLogos.tsx',
  'apps/web/src/components/storefront/ogabassey/components/Footer.tsx',
  'apps/web/src/components/storefront/ogabassey/components/FooterAppPayments.tsx',
  'apps/web/src/components/storefront/ogabassey/components/utility-checkout.ts',
  'apps/web/src/config/platform.ts',
  'apps/web/src/lib/social.ts',
  'apps/web/src/app/(storefront)/[slug]/(content)/pages/about/about-page-client.tsx',
  'apps/web/src/components/storefront/templates/gadget-universe.tsx',
  'apps/web/src/components/storefront/templates/gadget-default-template.tsx',
  'apps/web/src/components/analytics/analytics-pixel-provider.tsx',
  'apps/web/src/components/analytics/facebook-pixel.tsx',
  'apps/web/src/components/analytics/snapchat-pixel.tsx',
  'apps/web/src/components/analytics/twitter-pixel.tsx',
  'apps/web/src/components/analytics/google-analytics.tsx',
  'apps/web/src/components/analytics/tiktok-pixel.tsx',
  'apps/web/src/components/analytics/google-store-widget.tsx',
  'apps/web/src/components/analytics/google-customer-reviews.tsx',
  'apps/web/src/components/analytics/google-store-widget-utils.ts',
  'apps/web/src/components/storefront/ogabassey/components/negotiation-modal-request.ts',
  'apps/web/src/components/storefront/ogabassey/components/negotiation-evidence.ts',
  'apps/web/src/components/storefront/ogabassey/pages/bnpl-launcher.tsx',
  'apps/web/src/components/storefront/ogabassey/pages/cart-page-wrapper.tsx',
  'apps/web/src/components/storefront/ogabassey/components/google-ad-bootstrap.ts',
  'apps/web/src/components/storefront/ogabassey/components/CartSidebar.tsx',
  'apps/web/src/components/storefront/ogabassey/components/BlogSnippet.tsx',
  'apps/web/src/components/storefront/ogabassey/components/chat/use-ogabassey-chat.ts',
  'apps/web/src/components/storefront/ogabassey/pages/checkout-page.tsx',
  'apps/web/src/components/storefront/checkout-identity-modal.tsx',
  'apps/web/src/components/storefront/checkout-auth-modal.tsx',
  'apps/web/src/components/storefront/ogabassey/components/CheckoutIdentityModal.tsx',
  'apps/web/src/components/storefront/ogabassey/pages/quiz-page-data.ts',
  'apps/web/src/components/storefront/new-template/checkout-page.tsx',
  'apps/web/src/components/storefront/new-template/footer.tsx',
  'apps/web/src/components/storefront/RepairBookingWizard.tsx',
  'apps/web/src/config/storefront-agent-routes.ts',
  'apps/web/src/config/storefront-cache.ts',
  'apps/web/src/config/storefront-cdn-cache-control.ts',
  'apps/web/src/config/storefront-feed-routes.ts',
  'apps/web/src/config/storefront-metadata-cache-bots.ts',
  'apps/web/src/lib/domain-cache-simple.ts',
  'apps/web/src/lib/credit-direct-client.ts',
  'apps/web/src/lib/credpal.ts',
  'apps/web/src/lib/klump-sdk.ts',
  'apps/web/src/lib/slug-alias-cache.ts',
  'apps/web/src/lib/storefront-blog-listing-status.ts',
  'apps/web/src/lib/storefront-blog-listing-verdict.ts',
  'apps/web/src/lib/storefront-blog-post-status.ts',
  'apps/web/src/lib/storefront-compare-hub-status.ts',
  'apps/web/src/lib/storefront-internal-preflight.ts',
  'apps/web/src/lib/storefront-preflight-rpc.ts',
  'apps/web/src/lib/storefront-slug-safety.ts',
  'apps/web/src/lib/storefront-document-home-path-rules.ts',
  'apps/web/src/lib/storefront-document-home-path.ts',
  'apps/web/src/lib/storefront-document-navigation.ts',
  'apps/web/src/lib/storefront-path-prefix.ts',
  'apps/web/src/lib/storefront-pdp-first-segment-gate.ts',
  'apps/web/src/lib/storefront-product-canonical-redirect.ts',
  'apps/web/src/lib/storefront-pdp-canonical-path.ts',
  'apps/web/src/lib/normalize-storefront-category-slug.ts',
  'apps/web/src/lib/seo-utils.ts',
  'apps/web/src/lib/storefront-product-slug-membership.ts',
  'apps/web/src/lib/storefront-route-identifier.ts',
  'apps/web/src/lib/storefront-unsafe-pdp-segments.ts',
  'apps/web/src/lib/posthog/config.ts',
  'apps/web/src/lib/google-places.ts',
  ...new Set(Object.values(STOREFRONT_EDGE_MACHINE_SOURCE_PATHS)),
  ...STOREFRONT_EDGE_PUBLIC_ASSET_ROWS.map(({ sourcePath }) => sourcePath),
  STOREFRONT_EDGE_PLATFORM_ROOT_FAVICON_ROW.sourcePath,
] as const;
