import type { ClusterSupport } from '@/config/storefront-content-cluster-shared';

const gamingBrands = {
  playstation: ['playstation', 'ps5', 'ps4', 'sony'],
  nintendo: ['nintendo', 'switch'],
  xbox: ['xbox', 'microsoft'],
  gaming: ['gaming', 'game'],
} as const;

const tvBrands = {
  samsung: ['samsung'],
  lg: ['lg'],
  hisense: ['hisense'],
  tcl: ['tcl'],
  sony: ['sony'],
} as const;

export const MEDIA_CONTENT_CLUSTER_SUPPORT = {
  audio: {
    categoryNames: ['audio', 'speakers', 'headphones', 'soundbars'],
    articleTokens: [
      'audio',
      'airpods',
      'earbuds',
      'headphones',
      'speaker',
      'soundbar',
      'jbl',
      'anc',
      'bluetooth',
      'battery',
    ],
    brandTokens: {
      apple: ['apple', 'airpods'],
      jbl: ['jbl'],
      samsung: ['samsung', 'galaxy buds'],
      riversong: ['riversong'],
      sony: ['sony'],
      'harman-kardon': ['harman', 'kardon'],
      google: ['google', 'pixel buds'],
    },
    priceBandAliases: {
      'under-100k': ['budget', 'cheap'],
      'under-300k': ['premium', 'anc'],
    },
  },
  earbuds: {
    categoryNames: ['earbuds', 'earphones', 'buds'],
    articleTokens: [
      'earbuds',
      'airpods',
      'buds',
      'earphones',
      'anc',
      'bluetooth',
      'battery',
      'case',
    ],
    brandTokens: {
      apple: ['apple', 'airpods'],
      samsung: ['samsung', 'galaxy buds'],
      google: ['google', 'pixel buds'],
      riversong: ['riversong'],
      jbl: ['jbl'],
    },
    priceBandAliases: {
      'under-100k': ['budget', 'cheap'],
      'under-300k': ['anc', 'premium'],
    },
  },
  smartwatches: {
    categoryNames: ['smartwatches', 'smart watches', 'watches'],
    articleTokens: [
      'smartwatch',
      'watch',
      'fitness',
      'heart rate',
      'battery',
      'pixel watch',
      'galaxy watch',
      'apple watch',
    ],
    brandTokens: {
      apple: ['apple', 'apple watch'],
      samsung: ['samsung', 'galaxy watch'],
      google: ['google', 'pixel watch'],
      riversong: ['riversong'],
    },
    priceBandAliases: {
      'under-100k': ['budget', 'fitness'],
      'under-300k': ['premium'],
    },
  },
  wearables: {
    categoryNames: ['wearables', 'fitness trackers', 'smart watches'],
    articleTokens: [
      'wearable',
      'smartwatch',
      'watch',
      'fitness',
      'tracker',
      'battery',
      'health',
    ],
    brandTokens: {
      apple: ['apple'],
      samsung: ['samsung'],
      google: ['google', 'pixel'],
      riversong: ['riversong'],
    },
    priceBandAliases: {
      'under-100k': ['budget', 'fitness'],
      'under-300k': ['premium'],
    },
  },
  printers: {
    categoryNames: ['printers', 'printer'],
    articleTokens: [
      'printer',
      'laserjet',
      'ink',
      'toner',
      'cartridge',
      'wireless',
      'office',
      'scanner',
    ],
    brandTokens: {
      hp: ['hp', 'laserjet', 'deskjet', 'smart tank'],
      canon: ['canon'],
      epson: ['epson'],
      brother: ['brother'],
    },
    priceBandAliases: {
      'under-300k': ['home office', 'budget'],
      'under-500k': ['office', 'wireless'],
    },
  },
  monitors: {
    categoryNames: ['monitors', 'monitor', 'displays'],
    articleTokens: [
      'monitor',
      'display',
      'refresh rate',
      'hz',
      'gaming monitor',
      'usb-c',
      '4k',
    ],
    brandTokens: {
      samsung: ['samsung'],
      hp: ['hp'],
      dell: ['dell'],
      lg: ['lg'],
      msi: ['msi'],
    },
    priceBandAliases: {
      'under-300k': ['budget', 'office'],
      'under-500k': ['gaming', '4k'],
    },
  },
  accessories: {
    categoryNames: ['accessories', 'chargers', 'cables', 'cases'],
    articleTokens: [
      'accessory',
      'charger',
      'cable',
      'adapter',
      'case',
      'stylus',
      'pen',
      'keyboard',
      'power bank',
    ],
    brandTokens: {
      apple: ['apple'],
      samsung: ['samsung'],
      xiaomi: ['xiaomi', 'redmi'],
      riversong: ['riversong'],
      targus: ['targus'],
      logitech: ['logitech'],
      hp: ['hp'],
    },
    priceBandAliases: {
      'under-100k': ['charger', 'case', 'cable'],
      'under-300k': ['keyboard', 'stylus'],
    },
  },
  'gaming-accessories': {
    categoryNames: ['gaming accessories', 'controllers'],
    articleTokens: [
      'controller',
      'dualsense',
      'dualshock',
      'gaming accessory',
      'headset',
      'dock',
    ],
    brandTokens: gamingBrands,
    priceBandAliases: { 'under-300k': ['controller', 'accessory'] },
  },
  'samsung-tvs': {
    categoryNames: ['samsung tvs', 'samsung tv'],
    articleTokens: [
      'samsung tv',
      'smart tv',
      'oled',
      'qled',
      '4k',
      'hdr',
      'gaming tv',
    ],
    brandTokens: tvBrands,
    priceBandAliases: {
      'under-500k': ['budget', 'entry-level'],
      'under-1m': ['midrange', '4k', 'family'],
    },
  },
  'lg-tvs': {
    categoryNames: ['lg tvs', 'lg tv'],
    articleTokens: ['lg tv', 'smart tv', 'oled', 'qned', '4k', 'hdr', 'webos'],
    brandTokens: tvBrands,
    priceBandAliases: {
      'under-500k': ['budget', 'entry-level'],
      'under-1m': ['midrange', '4k', 'family'],
    },
  },
  'smart-tvs': {
    categoryNames: ['smart tvs', 'smart tv', 'televisions', 'tvs'],
    articleTokens: [
      'tv',
      'television',
      'smart tv',
      'oled',
      'qled',
      'google tv',
      'android tv',
      '4k',
      'hdr',
    ],
    brandTokens: tvBrands,
    priceBandAliases: {
      'under-500k': ['budget', 'entry-level', 'cheap'],
      'under-1m': ['midrange', '4k', 'family'],
    },
  },
  'vr-headsets': {
    categoryNames: ['vr headsets', 'vr', 'virtual reality'],
    articleTokens: [
      'vr',
      'headset',
      'quest',
      'virtual reality',
      'mixed reality',
    ],
    brandTokens: {
      meta: ['meta', 'quest'],
      sony: ['sony', 'ps vr', 'psvr'],
      apple: ['apple', 'vision pro'],
    },
    priceBandAliases: { 'under-1m': ['quest', 'headset'] },
  },
} satisfies Record<string, ClusterSupport>;
