import type { ClusterSupport } from './storefront-content-cluster-shared';

const phoneBrands = {
  apple: ['apple', 'iphone', 'ios'],
  samsung: ['samsung', 'galaxy'],
  redmi: ['redmi', 'xiaomi'],
  xiaomi: ['xiaomi', 'redmi', 'poco'],
  tecno: ['tecno'],
  infinix: ['infinix'],
  itel: ['itel'],
  google: ['google', 'pixel'],
  oppo: ['oppo'],
  vivo: ['vivo'],
  honor: ['honor'],
} as const;

const laptopBrands = {
  hp: ['hp', 'elitebook', 'pavilion', 'omen'],
  dell: ['dell', 'latitude', 'xps', 'inspiron'],
  lenovo: ['lenovo', 'thinkpad', 'legion'],
  apple: ['apple', 'macbook'],
  asus: ['asus', 'rog', 'tuf'],
  msi: ['msi'],
} as const;

export const CORE_CONTENT_CLUSTER_SUPPORT = {
  smartphones: {
    categoryNames: ['smartphones', 'phones', 'mobile phones'],
    articleTokens: [
      'smartphone',
      'phone',
      'iphone',
      'android',
      'samsung',
      'galaxy',
      'redmi',
      'xiaomi',
      'tecno',
      'itel',
      'infinix',
      'pixel',
      'battery',
      'camera',
      '5g',
      'sim',
    ],
    brandTokens: phoneBrands,
    priceBandAliases: {
      'under-300k': ['budget', 'cheap', 'entry-level', 'affordable'],
      'under-500k': ['midrange', 'mid-range', 'under-500k', 'value'],
    },
  },
  laptops: {
    categoryNames: ['laptops', 'computers', 'notebooks'],
    articleTokens: [
      'laptop',
      'notebook',
      'macbook',
      'windows',
      'ssd',
      'ram',
      'gaming',
      'battery',
      'intel',
      'amd',
      'ryzen',
      'core i5',
      'core i7',
    ],
    brandTokens: laptopBrands,
    priceBandAliases: {
      'under-500k': ['budget', 'student', 'entry-level', 'cheap'],
      'under-1m': ['midrange', 'creator', 'office', 'work'],
    },
  },
  'gaming-laptops': {
    categoryNames: ['gaming laptops', 'gaming-laptops'],
    articleTokens: [
      'gaming laptop',
      'rtx',
      'geforce',
      'rog',
      'tuf',
      'omen',
      'legion',
      'msi',
      'refresh rate',
    ],
    brandTokens: laptopBrands,
    priceBandAliases: {
      'under-1m': ['budget gaming', 'entry gaming'],
      'under-2m': ['rtx', 'midrange gaming'],
    },
  },
  tablets: {
    categoryNames: ['tablets', 'tablet', 'ipad', 'pads'],
    articleTokens: [
      'tablet',
      'ipad',
      'tab',
      'pad',
      'stylus',
      'pencil',
      'keyboard',
      'student',
      'kids',
    ],
    brandTokens: {
      apple: ['apple', 'ipad'],
      samsung: ['samsung', 'galaxy tab'],
      xiaomi: ['xiaomi', 'redmi pad'],
      lenovo: ['lenovo'],
      honor: ['honor'],
      infinix: ['infinix'],
      itel: ['itel'],
      tecno: ['tecno'],
    },
    priceBandAliases: {
      'under-300k': ['budget', 'student', 'kids'],
      'under-500k': ['midrange', 'stylus'],
    },
  },
  'childrens-tablets': {
    categoryNames: ['childrens tablets', 'children tablets', 'kids tablets'],
    articleTokens: [
      'kids tablet',
      'children tablet',
      'parental control',
      'tablet',
      'education',
    ],
    brandTokens: {
      amazon: ['amazon', 'fire'],
      samsung: ['samsung'],
      lenovo: ['lenovo'],
    },
    priceBandAliases: { 'under-300k': ['kids', 'budget', 'school'] },
  },
  desktops: {
    categoryNames: ['desktops', 'desktop computers', 'pcs'],
    articleTokens: [
      'desktop',
      'pc',
      'all-in-one',
      'aio',
      'workstation',
      'mini pc',
    ],
    brandTokens: {
      hp: ['hp'],
      dell: ['dell', 'optiplex'],
      lenovo: ['lenovo'],
      apple: ['apple', 'imac', 'mac mini'],
    },
    priceBandAliases: {
      'under-500k': ['office', 'budget'],
      'under-1m': ['workstation', 'all-in-one'],
    },
  },
} satisfies Record<string, ClusterSupport>;
