import { StyleSheet } from 'react-native';
import { BRAND, palette, SPACING } from '@/constants/Colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: SPACING.lg,
  },
  iconContainer: { marginBottom: 24 },
  title: { fontSize: 24, fontWeight: '700', marginBottom: 8 },
  message: { fontSize: 16, textAlign: 'center', marginBottom: 32 },
  referenceText: {
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 24,
  },
  voucherCard: {
    width: '100%',
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 20,
  },
  voucherLabel: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  voucherCode: {
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0,
  },
  cashbackCard: {
    width: '100%',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    marginBottom: 24,
    backgroundColor: palette.emerald[50],
    borderColor: palette.emerald[200],
  },
  cashbackAmount: {
    fontSize: 16,
    fontWeight: '700',
    color: palette.emerald[600],
  },
  cashbackBalance: { fontSize: 13, color: palette.gray[500], marginTop: 2 },
  cashbackIcon: { marginBottom: 4 },
  upsellCard: {
    width: '100%',
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 24,
  },
  upsellTitle: { fontSize: 18, fontWeight: '600', marginBottom: 8 },
  upsellText: { fontSize: 14, marginBottom: 16 },
  primaryButton: {
    height: 50,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: { color: palette.white, fontSize: 16, fontWeight: '600' },
  secondaryButton: {
    width: '100%',
    height: 50,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  secondaryButtonText: { fontSize: 16, fontWeight: '600' },
  shareButton: {
    width: '100%',
    height: 50,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  shareButtonText: {
    color: BRAND.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  tokenButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    marginTop: 12,
    minHeight: 36,
    paddingHorizontal: 14,
  },
  tokenButtonText: {
    color: BRAND.primary,
    fontSize: 13,
    fontWeight: '700',
  },
});
