import { StyleSheet } from 'react-native';

export const customerCreateStyles = StyleSheet.create({
  content: { gap: 20, padding: 16, paddingBottom: 28 },
  section: { gap: 10 },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  sectionIcon: {
    alignItems: 'center',
    borderRadius: 10,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  sectionTitle: { fontSize: 15, fontWeight: '700' },
  nameRow: { flexDirection: 'row', gap: 12 },
  field: {
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 56,
    paddingHorizontal: 14,
  },
  fieldInput: { flex: 1, fontSize: 16, minHeight: 42, padding: 0 },
  phoneField: {
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 56,
    paddingHorizontal: 12,
  },
  countryButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    minHeight: 44,
    paddingRight: 10,
  },
  countryFlag: { fontSize: 18 },
  countryCode: { fontSize: 15, fontWeight: '700' },
  fieldDivider: { height: 28, marginRight: 12, width: 1 },
  countryDropdown: {
    borderRadius: 16,
    borderWidth: 1,
    gap: 10,
    padding: 10,
  },
  countrySearchRow: {
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  countryList: { maxHeight: 220 },
  countryRow: {
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
    padding: 12,
  },
  countryName: { fontSize: 14, fontWeight: '700' },
  addressIcon: { left: 16, position: 'absolute', top: 18, zIndex: 2 },
  typeToggle: {
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    padding: 4,
  },
  typeToggleOption: {
    alignItems: 'center',
    borderRadius: 10,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 44,
  },
  typeToggleLabel: { fontSize: 15, fontWeight: '700' },
});
