export const PETROCK_PRODUCT_SNAPSHOT_MAX_AGE_MS = 48 * 60 * 60 * 1000;
export const PETROCK_PRODUCT_PRICE_CEILING_MULTIPLIER = 1.25;
export const PETROCK_PRODUCT_PRICE_ALERT_MULTIPLIER = 1.15;
export const PETROCK_LOW_BALANCE_USD = 25;
export const PETROCK_DEFAULT_POLL_AFTER_MS = 2_000;
export const PETROCK_MAX_POLL_AFTER_MS = 60_000;
