import type { ShipmentTrackingStatus } from '../schemas/shipment-tracking-status';

const GIGL_STATUS_MAP: Readonly<Record<string, ShipmentTrackingStatus>> = {
  MCRT: 'booked',
  CRT: 'booked',
  CRH: 'booked',
  CRTGF: 'booked',
  CRTGH: 'booked',
  CRTUK: 'booked',
  ISE: 'booked',
  MAPT: 'pickup_scheduled',
  MENP: 'pickup_scheduled',
  DLP: 'pickup_scheduled',
  MPIK: 'picked_up',
  PICKED: 'picked_up',
  MSVC: 'in_transit',
  MDSE: 'in_transit',
  MAFD: 'in_transit',
  AISN: 'in_transit',
  DIWN: 'in_transit',
  APT: 'in_transit',
  CLC: 'in_transit',
  UCC: 'in_transit',
  DPC: 'in_transit',
  ADF: 'in_transit',
  MRTD: 'in_transit',
  ARP: 'in_transit',
  TRO: 'in_transit',
  DTR: 'in_transit',
  DLD: 'in_transit',
  AIWH: 'in_transit',
  IFA: 'in_transit',
  ARO: 'in_transit',
  DSC: 'in_transit',
  AST: 'in_transit',
  DST: 'in_transit',
  GOP: 'in_transit',
  ACC: 'in_transit',
  DCC: 'in_transit',
  SRIC: 'in_transit',
  IDK: 'in_transit',
  IDH: 'in_transit',
  MRTE: 'in_transit',
  SSR: 'in_transit',
  SRC: 'in_transit',
  DASH: 'in_transit',
  CLS: 'in_transit',
  MSHC: 'out_for_delivery',
  WC: 'out_for_delivery',
  OFDU: 'out_for_delivery',
  DFA: 'out_for_delivery',
  FID: 'out_for_delivery',
  ATD: 'out_for_delivery',
  MATD: 'out_for_delivery',
  OVDSHP: 'out_for_delivery',
  MAHD: 'delivered',
  SHD: 'delivered',
  OKC: 'delivered',
  OKT: 'delivered',
  MSCP: 'cancelled',
  SSC: 'cancelled',
  MSCC: 'cancelled',
  SRHUB: 'returned',
  VFSSRR: 'returned',
  SDR: 'failed',
  SHIPMENT_CREATED: 'booked',
  CREATED: 'booked',
  PENDING: 'pending',
  ASSIGNED_FOR_PICKUP: 'pickup_scheduled',
  PICKUP_SCHEDULED: 'pickup_scheduled',
  PICKED_UP: 'picked_up',
  COLLECTED: 'picked_up',
  IN_TRANSIT: 'in_transit',
  SHIPMENT_IN_TRANSIT: 'in_transit',
  PROCESSING: 'in_transit',
  DEPARTED: 'in_transit',
  ARRIVED: 'in_transit',
  OUT_FOR_DELIVERY: 'out_for_delivery',
  ON_DELIVERY: 'out_for_delivery',
  DELIVERED: 'delivered',
  SHIPMENT_DELIVERED: 'delivered',
  COMPLETED: 'delivered',
  CANCELLED: 'cancelled',
  CANCELED: 'cancelled',
  FAILED: 'failed',
  DELIVERY_FAILED: 'failed',
  RETURNED: 'returned',
  RETURNED_TO_SENDER: 'returned',
};

function normalizeProviderStatus(value: string): string {
  return value
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^a-z0-9]+/gi, '_')
    .replace(/^_+|_+$/g, '')
    .toUpperCase();
}

export function mapKnownGiglStatus(
  value: string
): ShipmentTrackingStatus | null {
  return GIGL_STATUS_MAP[normalizeProviderStatus(value)] ?? null;
}
