import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const ROOT = path.resolve(__dirname, '../..');

describe('SDK 56 compliance', () => {
  it('app.config.ts does not contain an explicit newArchEnabled override', () => {
    const configSource = readFileSync(
      path.join(ROOT, 'app.config.ts'),
      'utf-8'
    );
    expect(configSource).not.toContain('newArchEnabled');
  });

  it('sets SDK 56 iOS deployment settings to 16.4', () => {
    const configSource = readFileSync(
      path.join(ROOT, 'app.config.ts'),
      'utf-8'
    );

    expect(configSource).toContain("deploymentTarget: '16.4'");
    expect(configSource).toContain("minimumOSVersion: '16.4'");
    expect(configSource).not.toContain("minimumOSVersion: '15.1'");
  });

  it('defaults the admin iOS hardening plugin to the SDK 56 iOS floor', () => {
    const pluginSource = readFileSync(
      path.join(ROOT, 'plugins/with-ios-release-hardening.ts'),
      'utf-8'
    );
    const pluginRuntimeSource = readFileSync(
      path.join(ROOT, 'plugins/with-ios-release-hardening.js'),
      'utf-8'
    );

    expect(pluginSource).toContain("minimumOSVersion = '16.4'");
    expect(pluginSource).not.toContain("default: '16.0'");
    expect(pluginRuntimeSource).toContain("minimumOSVersion = '16.4'");
    expect(pluginRuntimeSource).not.toContain("minimumOSVersion = '16.0'");
    expect(pluginRuntimeSource).toContain('withEntitlementsPlist');
    expect(pluginRuntimeSource).not.toContain('Baci/Baci.Release.entitlements');
    expect(pluginRuntimeSource).not.toContain('Baci/Baci.Debug.entitlements');
  });

  it('gradle.properties does not contain newArchEnabled', () => {
    const filePath = path.join(ROOT, 'android/gradle.properties');
    if (!existsSync(filePath)) return; // generated by prebuild, gitignored
    const gradleProps = readFileSync(filePath, 'utf-8');
    // Expo prebuild may add newArchEnabled — only check source-controlled content
    const sourceLines = gradleProps
      .split('\n')
      .filter((l) => !l.startsWith('newArchEnabled'));
    expect(sourceLines.join('\n')).not.toContain('newArchEnabled');
  });

  it('Podfile.properties.json does not contain newArchEnabled', () => {
    const filePath = path.join(ROOT, 'ios/Podfile.properties.json');
    if (!existsSync(filePath)) return; // generated by prebuild, gitignored
    const podfileProps = readFileSync(filePath, 'utf-8');
    expect(podfileProps).not.toContain('newArchEnabled');
  });

  it('package.json does not contain expo-av', () => {
    const pkg = JSON.parse(
      readFileSync(path.join(ROOT, 'package.json'), 'utf-8')
    );
    expect(pkg.dependencies).not.toHaveProperty('expo-av');
  });

  it('package.json does not contain expo-blur (unused)', () => {
    const pkg = JSON.parse(
      readFileSync(path.join(ROOT, 'package.json'), 'utf-8')
    );
    expect(pkg.dependencies).not.toHaveProperty('expo-blur');
  });
});
