import { StyleSheet } from 'react-native';
import {
  RADIUS,
  SPACING,
  type ThemeColors,
  TYPOGRAPHY,
} from '@/constants/theme';

export const getMerchantSetupStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    headerBrand: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: SPACING.sm,
    },
    headerMark: {
      alignItems: 'center',
      backgroundColor: colors.primaryLight,
      borderRadius: RADIUS.md,
      height: 36,
      justifyContent: 'center',
      width: 36,
    },
    headerMeta: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: RADIUS.full,
      borderWidth: 1,
      color: colors.textSecondary,
      fontFamily: TYPOGRAPHY.fontFamily.medium,
      fontSize: TYPOGRAPHY.size.xs,
      overflow: 'hidden',
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.sm,
    },
    progressCard: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: RADIUS.lg,
      borderWidth: 1,
      gap: SPACING.md,
      padding: SPACING.md,
    },
    progressHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    progressTitle: {
      color: colors.text,
      fontFamily: TYPOGRAPHY.fontFamily.semiBold,
      fontSize: TYPOGRAPHY.size.sm,
    },
    progressCount: {
      color: colors.primary,
      fontFamily: TYPOGRAPHY.fontFamily.bold,
      fontSize: TYPOGRAPHY.size.sm,
    },
    stageTrack: {
      alignItems: 'flex-start',
      flexDirection: 'row',
    },
    stage: {
      alignItems: 'center',
      gap: SPACING.xs,
      width: 88,
    },
    stageDot: {
      alignItems: 'center',
      backgroundColor: colors.backgroundLight,
      borderColor: colors.border,
      borderRadius: RADIUS.full,
      borderWidth: 1,
      height: 28,
      justifyContent: 'center',
      width: 28,
    },
    stageDotActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    stageNumber: {
      color: colors.textSecondary,
      fontFamily: TYPOGRAPHY.fontFamily.bold,
      fontSize: TYPOGRAPHY.size.sm,
    },
    stageNumberActive: {
      color: colors.textOnPrimary,
    },
    stageLabel: {
      color: colors.textSecondary,
      fontFamily: TYPOGRAPHY.fontFamily.medium,
      fontSize: TYPOGRAPHY.size.xs,
      textAlign: 'center',
    },
    stageLabelActive: {
      color: colors.text,
      fontFamily: TYPOGRAPHY.fontFamily.semiBold,
    },
    stageConnector: {
      backgroundColor: colors.border,
      flex: 1,
      height: 2,
      marginHorizontal: -SPACING.sm,
      marginTop: 13,
      overflow: 'hidden',
    },
    stageConnectorComplete: {
      backgroundColor: colors.primary,
      height: '100%',
      width: '100%',
    },
    hero: {
      borderColor: colors.border,
      borderRadius: RADIUS.xl,
      borderWidth: 1,
      overflow: 'hidden',
    },
    heroGradient: {
      gap: SPACING.sm,
      padding: SPACING.xl,
    },
    heroEyebrowRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: SPACING.sm,
    },
    heroIcon: {
      alignItems: 'center',
      backgroundColor: colors.goldLight,
      borderRadius: RADIUS.md,
      height: 36,
      justifyContent: 'center',
      width: 36,
    },
    heroEyebrow: {
      color: colors.gold,
      fontFamily: TYPOGRAPHY.fontFamily.bold,
      fontSize: TYPOGRAPHY.size.xs,
      letterSpacing: 1.1,
    },
    heroTitle: {
      color: colors.text,
      fontFamily: TYPOGRAPHY.fontFamily.extraBold,
      fontSize: TYPOGRAPHY.size['4xl'],
      lineHeight: 34,
    },
    heroText: {
      color: colors.textSecondary,
      fontFamily: TYPOGRAPHY.fontFamily.regular,
      fontSize: TYPOGRAPHY.size.md,
      lineHeight: 21,
    },
    heroBack: {
      alignItems: 'center',
      alignSelf: 'flex-start',
      flexDirection: 'row',
      gap: SPACING.xs,
      minHeight: 44,
    },
    heroBackText: {
      color: colors.primary,
      fontFamily: TYPOGRAPHY.fontFamily.semiBold,
      fontSize: TYPOGRAPHY.size.sm,
    },
    formCard: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: RADIUS.xl,
      borderWidth: 1,
      gap: SPACING.xl,
      padding: SPACING.lg,
      shadowColor: '#000',
      shadowOffset: { height: 6, width: 0 },
      shadowOpacity: 0.16,
      shadowRadius: 18,
      elevation: 4,
    },
    formCardHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: SPACING.md,
    },
    formCardIcon: {
      alignItems: 'center',
      backgroundColor: colors.primaryLight,
      borderRadius: RADIUS.md,
      height: 42,
      justifyContent: 'center',
      width: 42,
    },
    formCardHeadingGroup: {
      flex: 1,
      gap: 2,
    },
    formCardTitle: {
      color: colors.text,
      fontFamily: TYPOGRAPHY.fontFamily.bold,
      fontSize: TYPOGRAPHY.size.lg,
    },
    formCardSubtitle: {
      color: colors.textSecondary,
      fontFamily: TYPOGRAPHY.fontFamily.regular,
      fontSize: TYPOGRAPHY.size.sm,
    },
    cardFields: {
      gap: SPACING.xl,
    },
    actionSurface: {
      backgroundColor: colors.primary,
      borderRadius: RADIUS.lg,
      marginTop: SPACING.xs,
      overflow: 'hidden',
      shadowColor: colors.primary,
      shadowOffset: { height: 7, width: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 14,
      elevation: 6,
    },
    actionSurfaceDisabled: {
      opacity: 0.65,
    },
    actionPressable: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: SPACING.sm,
      justifyContent: 'center',
      minHeight: 58,
      paddingHorizontal: SPACING.xl,
    },
    actionText: {
      color: colors.textOnPrimary,
      fontFamily: TYPOGRAPHY.fontFamily.bold,
      fontSize: TYPOGRAPHY.size.lg,
    },
    actionIcon: {
      alignItems: 'center',
      backgroundColor: 'rgba(255,255,255,0.16)',
      borderRadius: RADIUS.full,
      height: 30,
      justifyContent: 'center',
      width: 30,
    },
  });
