#!/bin/sh
# Consumer scanners are sourced by retire-ollama.sh after its trusted primitives.
parse_systemd_words() { printf '%s\n' "$1" | awk 'BEGIN{sq=0;dq=0;esc=0;started=0;word=""}{for(i=1;i<=length($0);i++){c=substr($0,i,1);if(esc){word=word c;started=1;esc=0;continue}if(c=="\\"&&!sq){esc=1;continue}if(c=="\""&&!sq){dq=!dq;started=1;continue}if(c=="\047"&&!dq){sq=!sq;started=1;continue}if(c~/[ \t]/&&!sq&&!dq){if(started){print word;word="";started=0}continue}word=word c;started=1}}END{if(esc||sq||dq)exit 2;if(started)print word}'; }
consumer_file_fingerprint() { path=$1; [ -f "$path" ] && [ ! -L "$path" ] || return 2; real=$(readlink -f -- "$path") || return 2; [ "$real" = "$path" ] || return 2; raw=$(temp_path); { stat -c '%d:%i:%f:%s:%u:%g:%a' "$path"; findmnt -no TARGET,SOURCE,FSTYPE,OPTIONS --target "$path"; } >"$raw" || { rm -f "$raw"; return 2; }; identity=$(sha "$raw"); rm -f "$raw"; printf '%s|%s|%s\n' "$path" "$(sha "$path")" "$identity"; }
consumer_matches() { grep -q -Ei 'ollama|11434' "$1"; }
consumer_canonical_regular() { path=$1; [ -f "$path" ] && [ ! -L "$path" ] || return 2; real=$(readlink -f -- "$path") || return 2; [ -f "$real" ] && [ ! -L "$real" ] || return 2; printf '%s\n' "$real"; }
nginx_include_paths() { awk '/^[[:space:]]*include[[:space:]]+/{line=$0;sub(/^[[:space:]]*include[[:space:]]+/,"",line);sub(/[[:space:]]*(#.*)?$/, "", line);if(line!~/;$/){bad=1;next}sub(/;$/, "", line);if(line==""||line~/[[:space:]]/||line!~ /^\//){bad=1;next}print line}END{exit bad?2:0}' "$1"; }
scan_nginx_file() {
  path=$(consumer_canonical_regular "$1") || return 2; grep -Fqx "$path" "$NGINX_SEEN" >/dev/null 2>&1 && return 0; printf '%s\n' "$path" >>"$NGINX_SEEN" || return 2
  if consumer_matches "$path"; then consumer_file_fingerprint "$path" || return 2; else status=$?; [ "$status" -eq 1 ] || return "$status"; fi
  includes=$(temp_path); nginx_include_paths "$path" >"$includes" || { status=$?; rm -f "$includes"; return "$status"; }
  while IFS= read -r pattern || [ -n "$pattern" ]; do set +f; set -- $pattern; set -f; [ -e "$1" ] || { rm -f "$includes"; return 2; }; for candidate do target=$(consumer_canonical_regular "$candidate") || { rm -f "$includes"; return 2; }; if consumer_matches "$target"; then definition_record=$(consumer_file_fingerprint "$path") || { rm -f "$includes"; return 2; }; target_record=$(consumer_file_fingerprint "$target") || { rm -f "$includes"; return 2; }; printf '%s|%s\n' "$definition_record" "$target_record"; else status=$?; [ "$status" -eq 1 ] || { rm -f "$includes"; return "$status"; }; fi; scan_nginx_file "$target" || { status=$?; rm -f "$includes"; return "$status"; }; done; done <"$includes"; rm -f "$includes"
}
scan_nginx_definitions() { [ ! -e "$NGINX_ROOT" ] && return 0; [ -d "$NGINX_ROOT" ] && [ ! -L "$NGINX_ROOT" ] || return 2; NGINX_SEEN=$(temp_path); list=$(temp_path); find "$NGINX_ROOT" -type f >"$list" || { rm -f "$NGINX_SEEN" "$list"; return 2; }; while IFS= read -r path || [ -n "$path" ]; do scan_nginx_file "$path" || { status=$?; rm -f "$NGINX_SEEN" "$list"; return "$status"; }; done <"$list"; rm -f "$NGINX_SEEN" "$list"; }
compose_env_file_refs() { awk 'function indent(s){sub(/[^ ].*$/, "", s);return length(s)}function trim(s){sub(/^[[:space:]]+/,"",s);sub(/[[:space:]]+$/, "",s);return s}{if($0~/^[[:space:]]*#/||$0~/^[[:space:]]*$/)next;n=indent($0);if($0~/^[[:space:]]*env_file:[[:space:]]*/){line=$0;sub(/^[[:space:]]*env_file:[[:space:]]*/,"",line);line=trim(line);level=n;if(line==""){inside=1;next}if(line~/^[\[{]/){bad=1;next}print line;inside=0;next}if(inside){if(n<=level){inside=0}else if($0~/^[[:space:]]*-[[:space:]]+/){line=$0;sub(/^[[:space:]]*-[[:space:]]+/,"",line);line=trim(line);if(line~/^[\[{]/||line=="")bad=1;else print line}else bad=1}}END{exit bad?2:0}' "$1"; }
compose_env_file_path() { definition=$1; value=$2; parsed=$(temp_path); parse_systemd_words "$value" >"$parsed" || { rm -f "$parsed"; return 2; }; count=$(wc -l <"$parsed"); [ "$count" -eq 1 ] || { rm -f "$parsed"; return 2; }; IFS= read -r item <"$parsed" || { rm -f "$parsed"; return 2; }; rm -f "$parsed"; case "$item" in ''|/*|*'..'*) return 2;; esac; base=$(readlink -f -- "$(dirname "$definition")") || return 2; target=$(readlink -f -- "$base/$item") || return 2; case "$target" in "$base"/*) :;; *) return 2;; esac; consumer_canonical_regular "$target"; }
scan_compose_environment_files() { definition=$1; refs=$(temp_path); compose_env_file_refs "$definition" >"$refs" || { status=$?; rm -f "$refs"; return "$status"; }; while IFS= read -r ref || [ -n "$ref" ]; do target=$(compose_env_file_path "$definition" "$ref") || { rm -f "$refs"; return 2; }; if consumer_matches "$target"; then definition_record=$(consumer_file_fingerprint "$definition") || { rm -f "$refs"; return 2; }; target_record=$(consumer_file_fingerprint "$target") || { rm -f "$refs"; return 2; }; printf '%s|%s\n' "$definition_record" "$target_record"; else status=$?; [ "$status" -eq 1 ] || { rm -f "$refs"; return "$status"; }; fi; done <"$refs"; rm -f "$refs"; }
scan_compose_definitions() { list=$(temp_path); for root in $COMPOSE_ROOTS; do [ ! -e "$root" ] && continue; [ -d "$root" ] && [ ! -L "$root" ] || { rm -f "$list"; return 2; }; find "$root" -maxdepth 5 -type f \( -name 'docker-compose*.yml' -o -name 'docker-compose*.yaml' -o -name 'compose*.yml' -o -name 'compose*.yaml' -o -name 'Containerfile' \) >>"$list" || { rm -f "$list"; return 2; }; done; while IFS= read -r path || [ -n "$path" ]; do if consumer_matches "$path"; then consumer_file_fingerprint "$path" || { status=$?; rm -f "$list"; return "$status"; }; else status=$?; [ "$status" -eq 1 ] || { rm -f "$list"; return "$status"; }; fi; case "$path" in *Containerfile) ;; *) scan_compose_environment_files "$path" || { status=$?; rm -f "$list"; return "$status"; };; esac; done <"$list"; rm -f "$list"; }
systemd_runtime_inventory() { systemctl list-units --all --no-legend --plain --no-pager >"$1"; }
systemd_runtime_has_unit() { awk -v unit="$2" '$1 == unit {found=1} END {exit !found}' "$1"; }
scan_systemd_runtime_environment_files() { name=$1; value=$2; parsed=$(temp_path); parse_systemd_words "$value" >"$parsed" || { rm -f "$parsed"; return 2; }; while IFS= read -r item || [ -n "$item" ]; do optional=0; case "$item" in -/*) optional=1; item=${item#-};; /*) :;; *) rm -f "$parsed"; return 2;; esac; IFS= read -r annotation || { rm -f "$parsed"; return 2; }; case "$annotation" in '(ignore_errors=no)') [ "$optional" -eq 0 ] || { rm -f "$parsed"; return 2; };; '(ignore_errors=yes)') optional=1;; *) rm -f "$parsed"; return 2;; esac; if [ ! -e "$item" ]; then [ "$optional" -eq 1 ] && continue; rm -f "$parsed"; return 2; fi; target=$(consumer_canonical_regular "$item") || { rm -f "$parsed"; return 2; }; [ "${RECOVERY_RECORDS+x}" = x ] && recovery_record_environment "$target" "$optional"; if consumer_matches "$target" || printf '%s\n' "$value" | grep -q -Ei 'ollama|11434'; then printf '%s:%s|%s|%s|%s\n' "$name" "$target" "$(hash_text "EnvironmentFiles=$value")" "$(hash_text "$name")" "$(consumer_file_fingerprint "$target")"; else status=$?; [ "$status" -eq 1 ] || { rm -f "$parsed"; return "$status"; }; fi; done <"$parsed"; rm -f "$parsed"; }
scan_systemd_runtime_consumers() { units=$(temp_path); properties=$(temp_path); systemd_runtime_inventory "$units" || { status=$?; rm -f "$units" "$properties"; return "$status"; }; while read -r name _ || [ -n "$name" ]; do case "$name" in ''|"$UNIT"|"$TIMER") continue;; esac; if systemctl show --property=Environment --property=EnvironmentFiles --property=ExecStart --no-pager -- "$name" >"$properties"; then :; else status=$?; refreshed=$(temp_path); systemd_runtime_inventory "$refreshed" || { rm -f "$units" "$properties" "$refreshed"; return "$status"; }; if systemd_runtime_has_unit "$refreshed" "$name"; then rm -f "$units" "$properties" "$refreshed"; return "$status"; fi; rm -f "$refreshed"; continue; fi; while IFS= read -r property || [ -n "$property" ]; do case "$property" in EnvironmentFiles=*) scan_systemd_runtime_environment_files "$name" "${property#EnvironmentFiles=}" || { status=$?; rm -f "$units" "$properties"; return "$status"; };; *) if printf '%s\n' "$property" | grep -q -Ei 'ollama|11434'; then printf '%s:%s\n' "$name" "$(hash_text "$property")"; else status=$?; [ "$status" -eq 1 ] || { rm -f "$units" "$properties"; return "$status"; }; fi;; esac; done <"$properties"; done <"$units"; rm -f "$units" "$properties"; }
scan_systemd_consumers() { list=$(temp_path); environment_files=$(temp_path); for root in $SYSTEMD_ROOTS; do [ -d "$root" ] || continue; if grep -r -l -Ei 'ollama|11434' "$root" >>"$list"; then :; else status=$?; [ "$status" -eq 1 ] || { rm -f "$list" "$environment_files"; return "$status"; }; fi; if grep -r -H -E '^[[:space:]]*EnvironmentFile=' "$root" >>"$environment_files"; then :; else status=$?; [ "$status" -eq 1 ] || { rm -f "$list" "$environment_files"; return "$status"; }; fi; done; while IFS= read -r path || [ -n "$path" ]; do case "$path" in */"$UNIT"|*/"$UNIT".d/*|*/"$TIMER"|*/"$TIMER".d/*) ;; *) consumer_file_fingerprint "$path" || { status=$?; rm -f "$list" "$environment_files"; return "$status"; };; esac; done <"$list"; rm -f "$list"; while IFS=: read -r definition directive || [ -n "$definition$directive" ]; do case "$definition" in */"$UNIT"|*/"$UNIT".d/*|*/"$TIMER"|*/"$TIMER".d/*) continue;; esac; value=${directive#*=}; parsed=$(temp_path); parse_systemd_words "$value" >"$parsed" || { status=$?; rm -f "$parsed"; return "$status"; }; while IFS= read -r item || [ -n "$item" ]; do optional=0; case "$item" in -*) optional=1; item=${item#-};; esac; case "$item" in /*) :;; *) rm -f "$parsed"; return 2;; esac; if [ ! -e "$item" ]; then [ "$optional" -eq 1 ] && continue; rm -f "$parsed"; return 2; fi; [ -f "$item" ] && [ ! -L "$item" ] || { rm -f "$parsed"; return 2; }; [ "${RECOVERY_RECORDS+x}" = x ] && recovery_record_environment "$item" "$optional"; if consumer_matches "$item"; then definition_record=$(consumer_file_fingerprint "$definition") || { status=$?; rm -f "$parsed"; return "$status"; }; item_record=$(consumer_file_fingerprint "$item") || { status=$?; rm -f "$parsed"; return "$status"; }; printf '%s|%s\n' "$definition_record" "$item_record"; else status=$?; [ "$status" -eq 1 ] || { rm -f "$parsed"; return "$status"; }; fi; done <"$parsed"; rm -f "$parsed"; done <"$environment_files"; rm -f "$environment_files"; scan_systemd_runtime_consumers; }
