import { BRAND, RADIUS, SPACING, TYPOGRAPHY } from '@/constants/Colors';
import { WALLET_COLORS } from './wallet.colors';

const COMPACT_PADDING_Y = 6;
const DISABLED_BALANCE_OPACITY = 0.6;

export const walletHeroStyles = {
  walletHero: {
    marginHorizontal: SPACING.md,
    marginTop: 0,
    borderRadius: RADIUS['3xl'],
    padding: SPACING.lg,
    backgroundColor: WALLET_COLORS.heroBackground,
    borderWidth: 1,
    borderColor: WALLET_COLORS.heroOutline,
  },
  walletHeroHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  walletHeroTitle: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size['2xl'],
    fontWeight: TYPOGRAPHY.weight.bold,
  },
  addMoneyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    borderRadius: RADIUS.full,
    paddingVertical: COMPACT_PADDING_Y,
    paddingHorizontal: SPACING.sm,
    borderWidth: 1,
    borderColor: WALLET_COLORS.heroBorder,
  },
  addMoneyButtonText: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  balanceLabel: {
    color: WALLET_COLORS.mutedText,
    fontSize: TYPOGRAPHY.size.base,
    fontWeight: TYPOGRAPHY.weight.medium,
    marginTop: SPACING.md,
  },
  balanceAmount: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size['4xl'],
    fontWeight: TYPOGRAPHY.weight.black,
    marginTop: SPACING.sm,
  },
  fundingAccountPill: {
    marginTop: SPACING.md,
    borderRadius: RADIUS.full,
    backgroundColor: WALLET_COLORS.white,
    paddingVertical: SPACING.sm,
    paddingLeft: SPACING.md,
    paddingRight: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  fundingAccountTextWrap: {
    flex: 1,
  },
  fundingAccountText: {
    color: WALLET_COLORS.fundingText,
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  fundingAccountCopyButton: {
    width: 28,
    height: 28,
    borderRadius: RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: WALLET_COLORS.fundingCopyBackground,
  },
  copyFeedbackText: {
    color: WALLET_COLORS.mutedText,
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.weight.medium,
    marginTop: SPACING.xs,
  },
  createAccountButton: {
    marginTop: SPACING.md,
    borderWidth: 1,
    borderColor: WALLET_COLORS.heroBorder,
    borderRadius: RADIUS.full,
    paddingVertical: SPACING.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: WALLET_COLORS.white,
  },
  createAccountButtonDisabled: {
    opacity: 0.65,
  },
  createAccountButtonText: {
    color: BRAND.primary,
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  createAccountUnavailableText: {
    color: WALLET_COLORS.mutedText,
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.weight.medium,
    lineHeight: 16,
    marginTop: SPACING.xs,
    textAlign: 'center',
  },
  balanceSummaryRow: {
    marginTop: SPACING.lg,
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: WALLET_COLORS.heroBorder,
    paddingTop: SPACING.md,
  },
  balanceSummaryCell: {
    flex: 1,
    alignItems: 'center',
    gap: SPACING.xs,
  },
  balanceSummaryLabel: {
    color: WALLET_COLORS.mutedText,
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.weight.semibold,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  balanceSummaryValue: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size.lg,
    fontWeight: TYPOGRAPHY.weight.bold,
  },
  balanceSummaryDivider: {
    width: 1,
    backgroundColor: WALLET_COLORS.heroBorder,
  },
  utilityPillsDivider: {
    marginTop: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: WALLET_COLORS.heroBorder,
  },
  utilityPillsLabel: {
    color: WALLET_COLORS.mutedText,
    fontSize: 10,
    fontWeight: TYPOGRAPHY.weight.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginTop: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  utilityPillsScroll: {
    flexDirection: 'row',
    gap: SPACING.sm,
    paddingBottom: 2,
  },
  utilityPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    borderRadius: RADIUS.full,
    backgroundColor: WALLET_COLORS.quickSaveBackground,
    borderWidth: 1,
    borderColor: WALLET_COLORS.heroBorder,
    paddingHorizontal: SPACING.md,
    paddingVertical: 8,
  },
  utilityPillText: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  loyaltyTierBadgeCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: RADIUS.full,
    marginTop: 4,
  },
  loyaltyTierTextCompact: {
    color: WALLET_COLORS.loyaltyTierText,
    fontSize: 9,
    fontWeight: TYPOGRAPHY.weight.bold,
    textTransform: 'uppercase',
  },
  primaryActionRow: {
    marginHorizontal: SPACING.md,
    marginTop: SPACING.md,
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  primaryActionButton: {
    flex: 1,
    borderRadius: RADIUS.xl,
    backgroundColor: BRAND.primary,
    paddingVertical: SPACING.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: SPACING.xs,
  },
  primaryActionButtonText: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size.base,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  secondaryActionButton: {
    flex: 1,
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    borderColor: WALLET_COLORS.secondaryBorder,
    backgroundColor: WALLET_COLORS.white,
    paddingVertical: SPACING.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: SPACING.xs,
  },
  secondaryActionButtonText: {
    fontSize: TYPOGRAPHY.size.base,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  quickSaveButton: {
    marginHorizontal: SPACING.md,
    marginTop: SPACING.sm,
    borderRadius: RADIUS.xl,
    backgroundColor: WALLET_COLORS.quickSaveBackground,
    paddingVertical: SPACING.sm,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: SPACING.xs,
  },
  quickSaveButtonText: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  balanceActions: {
    flexDirection: 'row',
    marginTop: SPACING.lg,
    paddingTop: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: WALLET_COLORS.balanceDivider,
  },
  balanceAction: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
  },
  balanceActionText: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size.base,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  disabledBalanceAction: {
    opacity: DISABLED_BALANCE_OPACITY,
  },
  divider: {
    width: 1,
    backgroundColor: WALLET_COLORS.balanceDivider,
  },
} as const;
