import fs from 'node:fs';
import path from 'node:path';
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !serviceRoleKey) {
    console.error('Missing Supabase credentials');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, serviceRoleKey);
const BUCKET_NAME = 'images';
const TARGET_SLUG = 'macbook-pro-m4-max-36gb-1tb-16-inch';
const LOCAL_IMAGE_PATH = path.resolve(process.cwd(), 'macbook_pro_m4_max.png'); // Image generated by tool

async function fixImage() {
    console.log(`🚀 Fixing image for ${TARGET_SLUG}...`);

    if (!fs.existsSync(LOCAL_IMAGE_PATH)) {
        console.error(`❌ Local image not found at ${LOCAL_IMAGE_PATH}`);
        // Try to find it in artifacts if not in CWD, but tool puts it in artifacts usually.
        // We will assume the tool output path or copy it.
        return;
    }

    const fileBuffer = fs.readFileSync(LOCAL_IMAGE_PATH);
    const uploadPath = `products/laptops/${TARGET_SLUG}.png`;

    console.log('Uploading to Supabase Storage...');
    const { data: uploadData, error: uploadError } = await supabase.storage
        .from(BUCKET_NAME)
        .upload(uploadPath, fileBuffer, {
            contentType: 'image/png',
            upsert: true,
        });

    if (uploadError) {
        console.error('❌ Upload failed:', uploadError.message);
        return;
    }

    const { data: { publicUrl } } = supabase.storage
        .from(BUCKET_NAME)
        .getPublicUrl(uploadPath);

    console.log(`✅ Uploaded to: ${publicUrl}`);

    console.log('Updating database...');
    const { error: dbError } = await supabase
        .from('products')
        .update({ images: [publicUrl] })
        .eq('slug', TARGET_SLUG);

    if (dbError) {
        console.error('❌ Database update failed:', dbError.message);
    } else {
        console.log('✨ Success! Database updated.');
    }
}

fixImage();
