import type { ImeiServiceTierDefinition } from './service-tier-types';

/**
 * Serial-based Apple services. Most target the non-iPhone families (iPad, Mac,
 * Watch), but a few (Serial Info, GSX Premium, Repair Eligibility, Replacement
 * History) also apply to iPhones via their serial — hence `smartphone` in their
 * `deviceCategories`. Sickw accepts an Apple serial in the same `imei` param, so
 * these are gated by our serial-input mode. Prices follow the catalog's blended
 * ~₦16,350/$ markup.
 */
export const APPLE_DEVICE_IMEI_SERVICE_TIERS = {
  serialInfo: {
    providerServiceId: '26',
    name: 'Serial Info',
    tagline: 'Identify from serial',
    description: 'Identify an Apple device from its serial number',
    detail:
      'Identifies the exact Apple model, family and specs from a serial number.',
    price: 200,
    costUsd: 0.01,
    features: ['Apple Model', 'Device Family', 'Serial Lookup'],
    checksIncluded: ['device', 'modelNumber', 'serialNumber'],
    icon: 'barcode-outline',
    brandScopes: ['apple'],
    deviceCategories: ['smartphone', 'tablet', 'laptop', 'watch'],
    identifier: 'serial',
  },
  icloudCleanLost: {
    providerServiceId: '4',
    name: 'iCloud Clean/Lost',
    tagline: 'Clean or reported lost?',
    description: 'iCloud clean or lost status',
    detail:
      'Checks whether the device is clean or marked lost in iCloud records.',
    price: 500,
    costUsd: 0.03,
    features: ['Clean/Lost Status', 'iCloud Risk', 'Device Model'],
    checksIncluded: ['device', 'modelNumber', 'icloud'],
    icon: 'lock-closed-outline',
    brandScopes: ['apple'],
    deviceCategories: ['smartphone', 'tablet', 'laptop'],
    identifier: 'both',
  },
  macIcloud: {
    providerServiceId: '110',
    name: 'Mac iCloud Lock',
    tagline: 'Is the Mac iCloud-locked?',
    description: 'MacBook & iMac iCloud on/off status',
    detail:
      'Checks whether a MacBook or iMac has Activation/iCloud lock enabled before you buy.',
    price: 3300,
    costUsd: 0.2,
    features: ['iCloud On/Off', 'Activation Lock Risk', 'Mac Model'],
    checksIncluded: ['device', 'modelNumber', 'icloud'],
    icon: 'laptop-outline',
    brandScopes: ['apple'],
    deviceCategories: ['laptop'],
    // Laptop-only: MacBooks/iMacs have no IMEI, only a serial.
    identifier: 'serial',
  },
  soldByCountry: {
    providerServiceId: '27',
    name: 'Sold By & Country',
    tagline: 'Where was it sold?',
    description: 'Apple sold-by channel and purchase country',
    detail:
      'Shows where and by whom the iPad, Mac or Watch was originally sold.',
    price: 29400,
    costUsd: 1.8,
    features: ['Sold-By Channel', 'Purchase Country', 'Purchase Date'],
    checksIncluded: [
      'device',
      'modelNumber',
      'purchaseCountry',
      'purchaseDate',
    ],
    icon: 'globe-outline',
    brandScopes: ['apple'],
    deviceCategories: ['tablet', 'laptop', 'watch'],
    identifier: 'serial',
  },
  gsxPremium: {
    providerServiceId: '63',
    name: 'GSX Premium Report',
    tagline: 'Deep Apple GSX report',
    description: 'Full Apple GSX premium details',
    detail:
      'The deepest Apple report: warranty, coverage, repairs, replacements and activation from Apple GSX.',
    price: 32700,
    costUsd: 2.0,
    features: [
      'Warranty & AppleCare',
      'Repair & Case History',
      'Replacement History',
      'Purchase Country',
      'Activation Status',
    ],
    checksIncluded: [
      'device',
      'modelNumber',
      'serialNumber',
      'warranty',
      'gsxCoverage',
      'repairHistory',
      'replacementHistory',
      'purchaseCountry',
      'activationStatus',
    ],
    icon: 'hardware-chip-outline',
    brandScopes: ['apple'],
    deviceCategories: ['smartphone', 'tablet', 'laptop', 'watch'],
    identifier: 'serial',
  },
  gsxRepairs: {
    providerServiceId: '68',
    name: 'Repairs & Coverage',
    tagline: 'Was it repaired?',
    description: 'Apple GSX cases, repairs and coverage',
    detail:
      'Shows Apple repair/case history and current warranty coverage for the device.',
    price: 19600,
    costUsd: 1.2,
    features: ['Repair History', 'Case History', 'Warranty Coverage'],
    checksIncluded: ['device', 'modelNumber', 'repairHistory', 'gsxCoverage'],
    icon: 'construct-outline',
    brandScopes: ['apple'],
    deviceCategories: ['tablet', 'laptop', 'watch'],
    identifier: 'serial',
  },
  repairEligibility: {
    providerServiceId: '77',
    name: 'Repair Eligibility',
    tagline: 'Can Apple service it?',
    description: 'Apple GSX repair eligibility',
    detail:
      'Checks whether the device is eligible for Apple service and its warranty state.',
    price: 2300,
    costUsd: 0.14,
    features: ['Repair Eligibility', 'Warranty State', 'Device Model'],
    checksIncluded: ['device', 'modelNumber', 'repairEligibility', 'warranty'],
    icon: 'build-outline',
    brandScopes: ['apple'],
    deviceCategories: ['smartphone', 'tablet', 'laptop', 'watch'],
    identifier: 'serial',
  },
  replacementHistory: {
    providerServiceId: '29',
    name: 'Replacement History',
    tagline: 'Original or replaced?',
    description: 'Apple replacement history',
    detail:
      'Shows whether the device was replaced by Apple and its replacement lineage.',
    price: 11500,
    costUsd: 0.7,
    features: ['Replacement Status', 'Device Lineage', 'Apple GSX'],
    checksIncluded: ['device', 'modelNumber', 'replacementHistory'],
    icon: 'refresh-outline',
    brandScopes: ['apple'],
    deviceCategories: ['smartphone', 'tablet', 'laptop', 'watch'],
    identifier: 'serial',
  },
} as const satisfies Record<string, ImeiServiceTierDefinition>;
