import type { ImeiServiceTierDefinition } from './service-tier-types';

export const ANDROID_IMEI_SERVICE_TIERS = {
  samsung: {
    providerServiceId: '80',
    name: 'Samsung Info',
    tagline: 'Samsung device info',
    description: 'Basic Samsung device info',
    detail: 'Basic Samsung device information from IMEI.',
    price: 1000,
    costUsd: 0.06,
    features: ['Samsung Model', 'Device Info', 'IMEI Lookup'],
    checksIncluded: ['device', 'modelNumber'],
    icon: 'phone-portrait-outline',
    brandScopes: ['samsung'],
  },
  samsungPro: {
    providerServiceId: '1',
    name: 'Samsung Info PRO',
    tagline: 'Detailed Samsung info',
    description: 'Detailed Samsung device info',
    detail: 'A deeper Samsung device information check.',
    price: 1500,
    costUsd: 0.1,
    features: ['Samsung Model', 'Detailed Device Info', 'IMEI Lookup'],
    checksIncluded: ['device', 'modelNumber'],
    icon: 'phone-portrait-outline',
    brandScopes: ['samsung'],
  },
  miLock: {
    providerServiceId: '206',
    name: 'Mi Lock Check',
    tagline: 'Xiaomi account lock',
    description: 'Xiaomi, Redmi and Poco account lock status',
    detail: 'Checks Xiaomi, Redmi and Poco account lock status.',
    price: 1500,
    costUsd: 0.1,
    features: ['Mi Lock Status', 'Xiaomi / Redmi / Poco', 'Device Info'],
    checksIncluded: ['device', 'modelNumber', 'miLockStatus'],
    icon: 'lock-closed-outline',
    brandScopes: ['android'],
  },
  miLostPro: {
    providerServiceId: '58',
    name: 'Mi Lost Check PRO',
    tagline: 'Clean or lost?',
    description: 'Xiaomi, Redmi and Poco clean/lost status',
    detail:
      'Checks whether a Xiaomi, Redmi or Poco device appears clean or lost.',
    price: 8000,
    costUsd: 0.5,
    features: ['Mi Lock Clean/Lost', 'Xiaomi / Redmi / Poco', 'Device Info'],
    checksIncluded: ['device', 'modelNumber', 'miLockStatus', 'miLostStatus'],
    icon: 'shield-checkmark-outline',
    brandScopes: ['android'],
  },
  pixel: {
    providerServiceId: '42',
    name: 'Pixel Info',
    tagline: 'Google Pixel details',
    description: 'Google Pixel device info',
    detail: 'Google Pixel device information from IMEI.',
    price: 2000,
    costUsd: 0.12,
    features: ['Pixel Model', 'Device Info', 'IMEI Lookup'],
    checksIncluded: ['device', 'modelNumber'],
    icon: 'phone-portrait-outline',
    brandScopes: ['android'],
  },
  oppoRealme: {
    providerServiceId: '39',
    name: 'Oppo/Realme Info',
    tagline: 'Oppo, OnePlus, Realme',
    description: 'Oppo, OnePlus and Realme device info',
    detail: 'Device information for Oppo, OnePlus and Realme phones.',
    price: 3300,
    costUsd: 0.2,
    features: ['Oppo / OnePlus / Realme', 'Device Info', 'IMEI Lookup'],
    checksIncluded: ['device', 'modelNumber'],
    icon: 'phone-portrait-outline',
    brandScopes: ['android'],
  },
  transsion: {
    providerServiceId: '45',
    name: 'Tecno/Infinix Info',
    tagline: 'Tecno, Infinix, Itel',
    description: 'Tecno, Infinix, Itel and Sonim device info',
    detail: 'Device information for Tecno, Infinix, Itel and Sonim phones.',
    price: 500,
    costUsd: 0.03,
    features: ['Tecno / Infinix / Itel', 'Device Info', 'IMEI Lookup'],
    checksIncluded: ['device', 'modelNumber'],
    icon: 'phone-portrait-outline',
    brandScopes: ['android'],
  },
} as const satisfies Record<string, ImeiServiceTierDefinition>;
