import type { ImeiServiceTierDefinition } from './service-tier-types';

export const CORE_IMEI_SERVICE_TIERS = {
  full: {
    providerServiceId: '61',
    name: 'Full Report',
    tagline: 'Know everything',
    description: 'Complete device health report',
    detail:
      'Best first check for used iPhones: network, Find My and stolen/lost status in one report.',
    price: 1500,
    costUsd: 0.1,
    features: [
      'Device Model & Number',
      'Serial Number',
      'iCloud / Find My Status',
      'Blacklist / Stolen Status',
      'Carrier / Network Info',
      'SIM Lock Status',
      'Activation Status',
      'Purchase Date',
      'Purchase Country',
      'Warranty Status',
      'Refurbished / Demo Flags',
      'Trust Score',
      'Buy / No-Buy Verdict',
    ],
    checksIncluded: [
      'device',
      'modelNumber',
      'serialNumber',
      'icloud',
      'blacklistStatus',
      'carrier',
      'simLock',
      'activationStatus',
      'purchaseDate',
      'purchaseCountry',
      'warranty',
      'refurbished',
      'demoUnit',
      'verdict',
    ],
    icon: 'checkmark-circle-outline',
    recommended: true,
    brandScopes: ['all'],
  },
  blacklist: {
    providerServiceId: '54',
    name: 'Stolen Check',
    tagline: 'Is it reported stolen?',
    description: 'Is this phone reported stolen?',
    detail: 'Checks worldwide lost/stolen blacklist records before you pay.',
    price: 700,
    costUsd: 0.04,
    features: ['Device Model', 'Blacklist Status', 'GSMA Database'],
    checksIncluded: ['device', 'modelNumber', 'blacklistStatus'],
    icon: 'shield-outline',
    brandScopes: ['all'],
  },
  blacklistPro: {
    providerServiceId: '6',
    name: 'Stolen Check PRO',
    tagline: 'Deeper blacklist lookup',
    description: 'Deeper worldwide lost/stolen blacklist lookup',
    detail:
      'A deeper worldwide blacklist check for higher-risk devices or expensive purchases.',
    price: 2000,
    costUsd: 0.12,
    features: ['Worldwide Blacklist', 'Lost/Stolen Status', 'GSMA Database'],
    checksIncluded: ['device', 'modelNumber', 'blacklistStatus'],
    icon: 'shield-checkmark-outline',
    brandScopes: ['all'],
  },
  carrier: {
    providerServiceId: '103',
    name: 'Network Check',
    tagline: 'Will my SIM work?',
    description: 'iPhone carrier and network info',
    detail:
      'Shows the iPhone carrier/network so you know what network it belongs to.',
    price: 1000,
    costUsd: 0.06,
    features: ['Original Carrier', 'Network Info', 'Device Model'],
    checksIncluded: ['device', 'modelNumber', 'carrier'],
    icon: 'globe-outline',
    brandScopes: ['apple'],
  },
  simLock: {
    providerServiceId: '8',
    name: 'SIM Lock',
    tagline: 'Can it use any SIM?',
    description: 'Check if the iPhone is locked to one carrier',
    detail:
      'Checks whether the iPhone is locked to one carrier or open for other SIM cards.',
    price: 500,
    costUsd: 0.025,
    features: ['SIM Lock Status', 'Carrier Lock Risk', 'Device Model'],
    checksIncluded: ['device', 'modelNumber', 'simLock'],
    icon: 'phone-portrait-outline',
    brandScopes: ['apple'],
  },
  icloud: {
    providerServiceId: '3',
    name: 'Find My Check',
    tagline: 'Is Find My on?',
    description: 'Find My iPhone status',
    detail:
      'Checks whether Find My/iCloud lock is on before you buy the device.',
    price: 300,
    costUsd: 0.02,
    features: ['Find My Status', 'iCloud Lock Risk', 'Device Model'],
    checksIncluded: ['device', 'modelNumber', 'icloud'],
    icon: 'lock-closed-outline',
    brandScopes: ['apple'],
  },
  carrierFmi: {
    providerServiceId: '78',
    name: 'Network + Find My',
    tagline: 'Carrier and FMI',
    description: 'Carrier and Find My status in one Apple check',
    detail:
      'Combines carrier/network information with Find My status for Apple devices.',
    price: 1300,
    costUsd: 0.08,
    features: ['Carrier Info', 'Find My Status', 'Device Model'],
    checksIncluded: ['device', 'modelNumber', 'carrier', 'icloud'],
    icon: 'globe-outline',
    brandScopes: ['apple'],
  },
  basic: {
    providerServiceId: '203',
    name: 'Quick ID',
    tagline: 'What phone is this?',
    description: 'Identify brand and model from IMEI or serial',
    detail: 'Identifies the brand and model from an IMEI or serial number.',
    price: 300,
    costUsd: 0.02,
    features: ['Brand', 'Device Model', 'Model Number'],
    checksIncluded: ['device', 'modelNumber'],
    icon: 'phone-portrait-outline',
    brandScopes: ['all'],
  },
} as const satisfies Record<string, ImeiServiceTierDefinition>;
