import type { ImeiServiceTierDefinition } from './service-tier-types';

/**
 * Phase 3 Petrock-only catalog candidates. They are intentionally omitted from
 * PUBLIC_IMEI_SERVICE_TIERS until a captured replay proves every promised field.
 * The provider id is a sentinel: real Petrock ids stay in the web server bundle.
 */
export const PETROCK_DEVICE_IMEI_SERVICE_TIERS = {
  esimCompatibility: {
    providerServiceId: 'petrock-only',
    name: 'eSIM Compatibility',
    tagline: 'Will this device use eSIM?',
    description: 'Check Apple eSIM support before buying or travelling',
    detail: 'Shows whether the device supports an electronic SIM profile.',
    price: 700,
    costUsd: 0.04,
    features: ['eSIM Compatibility', 'Device Model', 'IMEI Lookup'],
    checksIncluded: ['device', 'modelNumber', 'esimCompatibility'],
    icon: 'radio-outline',
    brandScopes: ['apple'],
    deviceCategories: ['smartphone', 'tablet'],
    identifier: 'imei',
  },
  refurbishedStatus: {
    providerServiceId: 'petrock-only',
    name: 'Refurbished Status',
    tagline: 'Original or refurbished?',
    description: 'Check whether Apple records identify a refurbished device',
    detail: 'Identifies factory-refurbished status from the device record.',
    price: 700,
    costUsd: 0.04,
    features: ['Refurbished Status', 'Device Model', 'Serial / IMEI Lookup'],
    checksIncluded: ['device', 'modelNumber', 'refurbished'],
    icon: 'refresh-outline',
    brandScopes: ['apple'],
    deviceCategories: ['smartphone', 'tablet', 'laptop', 'watch'],
    identifier: 'both',
  },
  replacementStatus: {
    providerServiceId: 'petrock-only',
    name: 'Replacement Status',
    tagline: 'Was it replaced?',
    description: 'Check whether Apple records identify a replacement device',
    detail: 'Shows replacement history available for the submitted device.',
    price: 700,
    costUsd: 0.04,
    features: ['Replacement Status', 'Device Model', 'Serial / IMEI Lookup'],
    checksIncluded: ['device', 'modelNumber', 'replacementHistory'],
    icon: 'refresh-outline',
    brandScopes: ['apple'],
    deviceCategories: ['smartphone', 'tablet', 'laptop', 'watch'],
    identifier: 'both',
  },
  applePartNumber: {
    providerServiceId: 'petrock-only',
    name: 'Apple Part Number',
    tagline: 'Identify the exact variant',
    description: 'Resolve Apple part and model identifiers',
    detail:
      'Returns the part number used to identify market and configuration.',
    price: 700,
    costUsd: 0.04,
    features: ['Part Number', 'Model Number', 'Device Family'],
    checksIncluded: ['device', 'modelNumber', 'partNumber'],
    icon: 'barcode-outline',
    brandScopes: ['apple'],
    deviceCategories: ['smartphone', 'tablet', 'laptop', 'watch'],
    identifier: 'both',
  },
  knoxEnrollment: {
    providerServiceId: 'petrock-only',
    name: 'Knox Enrollment',
    tagline: 'Company-managed Samsung?',
    description: 'Check Samsung Knox Mobile Enrollment status',
    detail: 'Shows whether the device is enrolled for enterprise management.',
    price: 1000,
    costUsd: 0.06,
    features: ['Knox Enrollment', 'Management Risk', 'Samsung Model'],
    checksIncluded: ['device', 'modelNumber', 'knoxEnrollment'],
    icon: 'briefcase-outline',
    brandScopes: ['samsung'],
    deviceCategories: ['smartphone'],
    identifier: 'imei',
  },
  samsungSoldBy: {
    providerServiceId: 'petrock-only',
    name: 'Samsung Sold By',
    tagline: 'Original seller and market',
    description: 'Check the original Samsung sales channel',
    detail: 'Returns available sold-by and market information for the device.',
    price: 700,
    costUsd: 0.04,
    features: ['Sold-By Channel', 'Device Model', 'Market Information'],
    checksIncluded: ['device', 'modelNumber', 'soldBy'],
    icon: 'storefront-outline',
    brandScopes: ['samsung'],
    deviceCategories: ['smartphone'],
    identifier: 'imei',
  },
  oneplusPremium: {
    providerServiceId: 'petrock-only',
    name: 'OnePlus Premium Info',
    tagline: 'Deeper OnePlus details',
    description: 'Premium model information for OnePlus devices',
    detail:
      'Identifies a OnePlus model and the available manufacturer details.',
    price: 700,
    costUsd: 0.04,
    features: ['OnePlus Model', 'Device Details', 'IMEI Lookup'],
    checksIncluded: ['device', 'modelNumber'],
    icon: 'phone-portrait-outline',
    brandScopes: ['oppo'],
    deviceCategories: ['smartphone'],
    identifier: 'imei',
  },
  transsionPremium: {
    providerServiceId: 'petrock-only',
    name: 'Tecno/Infinix Premium',
    tagline: 'Deeper Transsion details',
    description: 'Premium model information for Tecno, Infinix and Itel',
    detail: 'Identifies the device and available manufacturer details.',
    price: 700,
    costUsd: 0.04,
    features: ['Tecno / Infinix / Itel', 'Device Details', 'IMEI Lookup'],
    checksIncluded: ['device', 'modelNumber'],
    icon: 'phone-portrait-outline',
    brandScopes: ['tecno'],
    deviceCategories: ['smartphone'],
    identifier: 'imei',
  },
  macInfo: {
    providerServiceId: 'petrock-only',
    name: 'Mac Hardware Info',
    tagline: 'Identify this Mac',
    description: 'Mac model, serial and network hardware details',
    detail: 'Returns the available Mac identity and Wi-Fi MAC information.',
    price: 5000,
    costUsd: 0.3,
    features: ['Mac Model', 'Serial Number', 'Wi-Fi MAC'],
    checksIncluded: ['device', 'modelNumber', 'serialNumber', 'wifiMac'],
    icon: 'laptop-outline',
    brandScopes: ['apple'],
    deviceCategories: ['laptop'],
    identifier: 'serial',
  },
  macPhotoReport: {
    providerServiceId: 'petrock-only',
    name: 'Mac Photo Report',
    tagline: 'Hardware report with photo',
    description: 'Detailed Mac report with available device imagery',
    detail:
      'Returns model details and a provider-hosted device photo when available.',
    price: 9100,
    costUsd: 0.675,
    features: ['Mac Model', 'Serial Number', 'Device Photo'],
    checksIncluded: ['device', 'modelNumber', 'serialNumber', 'devicePhoto'],
    icon: 'image-outline',
    brandScopes: ['apple'],
    deviceCategories: ['laptop'],
    identifier: 'serial',
  },
  applePremium: {
    providerServiceId: 'petrock-only',
    name: 'Apple Premium Report',
    tagline: 'Deep Apple device report',
    description: 'Premium Apple identity, coverage and history report',
    detail: 'Combines the available device, warranty and replacement details.',
    price: 7900,
    costUsd: 0.75,
    features: ['Device Identity', 'Warranty', 'Replacement History'],
    checksIncluded: [
      'device',
      'modelNumber',
      'serialNumber',
      'warranty',
      'replacementHistory',
    ],
    icon: 'hardware-chip-outline',
    brandScopes: ['apple'],
    deviceCategories: ['smartphone', 'tablet'],
    identifier: 'both',
  },
  applePremiumMax: {
    providerServiceId: 'petrock-only',
    name: 'Apple Premium Max',
    tagline: 'Maximum Apple coverage',
    description: 'Highest-detail Apple device and service report',
    detail: 'Returns the broadest supported Apple identity and GSX data set.',
    price: 14_700,
    costUsd: 1.85,
    features: ['Device Identity', 'Coverage', 'Repair & Replacement History'],
    checksIncluded: [
      'device',
      'modelNumber',
      'serialNumber',
      'warranty',
      'gsxCoverage',
      'repairHistory',
      'replacementHistory',
    ],
    icon: 'hardware-chip-outline',
    brandScopes: ['apple'],
    deviceCategories: ['smartphone', 'tablet', 'laptop'],
    identifier: 'both',
  },
} as const satisfies Record<string, ImeiServiceTierDefinition>;
