export const merchantIdentityAuditFieldClassification = {
  exactFields: [
    'business_name',
    'country',
    'email_logo_url',
    'email_sender_name',
    'favicon_apple_touch_url',
    'favicon_png_192_url',
    'favicon_png_32_url',
    'favicon_svg_url',
    'is_published',
    'legal_entity_name',
    'logo_url',
    'site_description',
    'site_tagline',
    'site_title',
    'slug',
    'social_media',
    'support_email',
    'support_phone',
  ],
  presenceOnlyFields: [
    'business_address',
    'email',
    'lga_code',
    'phone',
    'registered_address',
    'state_code',
  ],
} as const;
