import { generateSlug } from '@/lib/seo-utils';

/**
 * Normalize a storefront category value into a slug-safe token.
 *
 * IMPORTANT: This must produce the *same* token that is stored in
 * `products.category_slug`, because callers use the result to filter products
 * by that column (e.g. in blog "related products" lookups). Product slugs
 * are generated by `generateSlug` in `normalize-product.ts`, so we delegate
 * to that same utility here instead of running an independent Unicode-aware
 * slugifier that produced subtly different tokens for values containing
 * diacritics (e.g. `Prodüct` → `product` vs. `prodct`).
 *
 * Returns `null` when the input is empty or cannot produce a usable token,
 * so callers can short-circuit the query instead of passing a falsy value
 * to `.eq()`.
 */
export function normalizeStorefrontCategoryValue(
  value: string | null | undefined
): string | null {
  if (typeof value !== 'string') {
    return null;
  }

  const normalized = generateSlug(value);

  return normalized || null;
}
