/**
 * Supabase/PostgREST projection for the product_key_specs relation.
 * Reuse this fragment in product queries so callers fetch the relation, not a
 * non-existent products.product_key_specs column. Keep fields aligned with the
 * product_key_specs table schema and with storefront consumers.
 */
export const PRODUCT_KEY_SPECS_RELATION_SELECT = `
  product_key_specs (
    screen_size_inches,
    refresh_rate_hz,
    chipset,
    ram_gb,
    storage_gb,
    main_camera_mp,
    battery_mah,
    charging_watt,
    has_5g,
    android_version,
    network_technology,
    sim_type,
    has_nfc,
    wifi_bands,
    bluetooth_version,
    usb_type,
    has_usb_otg,
    positioning,
    has_fm_radio,
    dimensions_mm,
    weight_g,
    build_materials,
    ip_rating,
    display_type,
    display_resolution,
    display_ppi,
    display_protection,
    display_peak_brightness,
    front_camera_mp,
    front_camera_features,
    front_camera_video,
    rear_camera_features,
    rear_camera_video,
    has_dual_camera,
    has_triple_camera,
    has_quad_camera,
    has_stereo_speakers,
    has_headphone_jack,
    fingerprint_type,
    sensors,
    battery_removable,
    has_wireless_charging,
    wireless_charging_watt,
    has_reverse_charging,
    cpu_cores,
    gpu,
    has_card_slot,
    card_slot_type,
    available_colors,
    model_numbers,
    announced_date,
    release_date,
    camera_score,
    battery_score,
    gaming_score,
    recommended_for,
    has_ois
  )
`;
