export const eventPipelineCredentialPaths = [
  [
    'apps/web/src/app/(platform)/onboarding/actions.ts',
    'apps/web/src/app/(platform)/onboarding/submit-onboarding-workflow.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/(platform)/onboarding/submit-onboarding-workflow.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/lib/storefront-product-purge-hostnames.ts',
    'apps/web/src/lib/cloudflare-purge.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/expo-push.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/expo-push.ts',
    'apps/web/src/lib/supabase/admin.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking-notifications/route.ts',
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/expo-push.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking-notifications/route.ts',
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/expo-push.ts',
    'apps/web/src/lib/supabase/admin.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/insurance/notify-activate-protection.ts',
    'apps/web/src/lib/expo-push.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/insurance/notify-activate-protection.ts',
    'apps/web/src/lib/supabase/admin.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking-notifications/route.ts',
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/insurance/notify-activate-protection.ts',
    'apps/web/src/lib/expo-push.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking-notifications/route.ts',
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/insurance/notify-activate-protection.ts',
    'apps/web/src/lib/supabase/admin.ts',
    'apps/web/src/env.ts',
  ],
] as const;
