export const eventPipelineAdminImporters = [
  'apps/web/src/app/api/cron/purge-jumia-self-authorization-discoveries/route.ts',
  'apps/web/src/app/api/marketplace/jumia/connect/exchange/route.ts',
  'apps/web/src/app/api/marketplace/jumia/connect/route.ts',
  'apps/web/src/app/api/marketplace/jumia/connect/ticket/route.ts',
  'apps/web/src/app/api/orders/route.ts',
  'apps/web/src/app/api/payments/juicyway/webhook/route.ts',
  'apps/web/src/app/api/platform/events/platform-event-forwarding.ts',
  'apps/web/src/lib/events/record-platform-order-created-event.ts',
  'apps/web/src/lib/expo-push.ts',
  'apps/web/src/lib/insurance/notify-activate-protection.ts',
  'apps/web/src/lib/jumia/jumia-authorization-refresh-lease.ts',
  'apps/web/src/lib/jumia/jumia-client-token-persistence.ts',
  'apps/web/src/lib/jumia/purge-expired-jumia-self-authorization-discoveries.ts',
] as const;
