export const eventPipelineCredentialPaths = [
  [
    'apps/web/src/app/(platform)/onboarding/actions.ts',
    'apps/web/src/app/(platform)/onboarding/submit-onboarding-workflow.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/(platform)/onboarding/submit-onboarding-workflow.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/lib/storefront-product-purge-hostnames.ts',
    'apps/web/src/lib/cloudflare-purge.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/expo-push.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/expo-push.ts',
    'apps/web/src/lib/supabase/admin.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking-notifications/route.ts',
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/expo-push.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking-notifications/route.ts',
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/expo-push.ts',
    'apps/web/src/lib/supabase/admin.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/insurance/notify-activate-protection.ts',
    'apps/web/src/lib/expo-push.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/insurance/notify-activate-protection.ts',
    'apps/web/src/lib/supabase/admin.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking-notifications/route.ts',
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/insurance/notify-activate-protection.ts',
    'apps/web/src/lib/expo-push.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/cron/gigl-tracking-notifications/route.ts',
    'apps/web/src/app/api/cron/gigl-tracking/gigl-tracking-notification-worker.ts',
    'apps/web/src/lib/insurance/notify-activate-protection.ts',
    'apps/web/src/lib/supabase/admin.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/internal/compare-page-status/[identifier]/route.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/lib/storefront-compare-page-hard-status.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/proxy.ts',
    'apps/web/src/lib/storefront-compare-page-hard-status.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/agentic/catalog/lookup/route.ts',
    'apps/web/src/lib/agentic/mutation-request.ts',
    'apps/web/src/lib/agentic/request-integrity.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/agentic/catalog/product/route.ts',
    'apps/web/src/lib/agentic/mutation-request.ts',
    'apps/web/src/lib/agentic/request-integrity.ts',
    'apps/web/src/env.ts',
  ],
  [
    'apps/web/src/app/api/agentic/catalog/search/route.ts',
    'apps/web/src/lib/agentic/mutation-request.ts',
    'apps/web/src/lib/agentic/request-integrity.ts',
    'apps/web/src/env.ts',
  ],
] as const;
