name: API Discovery

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  discover:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: API Discovery
        uses: apisec-inc/apisec-bolt-code-discovery-github-action@9c5e3d81e7830ca5347546e10c2b83ff42972a67 # v0.1.3
        with:
          api-endpoint: ${{ secrets.API_DISCOVERY_ENDPOINT }}
          api-token: ${{ secrets.API_DISCOVERY_TOKEN }}
          repo-path: "."
          dry-run: false
