name: API Discovery

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  discover:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: API Discovery
        uses: apisec-inc/apisec-bolt-code-discovery-github-action@674a812f6c53f3e627f669539e0be5bf0f4a3bc5 # v0.1.4
        with:
          api-endpoint: ${{ secrets.API_DISCOVERY_ENDPOINT }}
          api-token: ${{ secrets.API_DISCOVERY_TOKEN }}
          repo-path: "."
          dry-run: false
